### ISSUE TITLE
A practical algorithm for constraint resolution needs to be described.

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#118]
The approach of generating all possible combinations of settings and then culling the set is obviously not practical - the set of possible combinations is too large to be practical to enumerate. We should have one example in the document of a way to implement the algorithm that is more practical.

**Comment by alvestrand** [comment]
#28 changes the description of the algorithm, but not (I think) its implementability, so this bug applies both before and after the application of that change.

**Comment by alvestrand** [comment]
A draft document is being worked on:

https://docs.google.com/document/d/1-rM0-kaBn2vOMm5Om8aZW6IF9pFIpm5385D48HUWzWA/edit?usp=sharing

Still unclear if this needs to go in the document or not.

**Comment by jan-ivar** [comment]
Aren't these problems theoretical rather than important to solve in implementations?

#### Case 3: Linked configuration parameters

Last I checked, the Logitech C910 on Windows supports about 54 combinations of width/height/framerate/codec. The OSX camera driver seems to only like multiples of 40x30 and 128x72, in less than 25 working increments (multiplied by framerate I suppose).

Why not leave it to implementations to optimize prematurely?

#### Case 2: Orthogonal configuration parameters

Orthogonal capabilities are just that, orthogonal. E.g. a { zoom: { min: 0.0, max: 1.0 } } capability would work the same regardless of other settings, which in practical terms means that "constraining on width/height/zoom" is no more interesting than constraining on width/height and then "setting" (constraining) zoom on the result.

Said differently: A settings dictionary of { width: 640, height: 480, zoom: x } where x allows any legal zoom value, is the logical aggregate of an infinite number of sets that lets you stick with the Case 1 algorithm. Since x adapts (by the algorithm effectively ignoring x) it has no 'actual' value and would not contribute fitness distance.

I realize this sounds like your min-max triplet, but why track changes to x at all, except to support contradictory combinations in the advanced algorithm?

    advanced: [ { zoom: { max: 0.2 }, width: 640 },
                { zoom: { min: 0.3 }, width: 800 } ]

And why would anyone care about such nonsensical cases?

**Comment by alvestrand** [comment]
Zoom is a more hairy issue, since zoom actions (the mechanical type, not the "electronic zoom" action of cut-the-scene-down-ad-resize) take time to complete. Please don't introduce it here.

If the issue is not important to solve, it doesn't need to go in the document. I was challenged on whether the specification was implementable, so I produced something showing that it was. If it's obvious that it's implementable, the doc doesn't need to say anything about it.

**Comment by jan-ivar** [comment]
Sorry, zoom was a bad example. I struggled with finding a video-equivalent example as orthogonal as something like volume. Focus maybe? Doesn't matter.

I'm not saying implementation is obvious! Strictly speaking, supporting the contradictory advanced cases I'm dismissing seem required by the spec, and would need something like your min-max triplet to solve. I'm more lamenting that we still have the advanced algorithm, I suppose, and that some of the problems it raises are confusingly not useful to solve. Generality bites.

**Comment by fluffy** [comment]
Just to follow up on the obvious of this or not, have either of Chrome or FF implemented something that meets the spec that we could use as a pointer to "here is one way to do this" ?

**Comment by jan-ivar** [comment]
Firefox 38 implements the ideal algorithm, and 39 [internally treats](http://mxr.mozilla.org/mozilla-central/source/dom/media/webrtc/MediaEngineCameraVideoSource.cpp?rev=ce72894838de&mark=119-120#115) width == 0, height == 0 or frameRate == 0  on the *capability* (not the constraint) as "can do any" i.e. orthogonal.

Basically, if a capability is zero ("can do any") then it contributes zero to fitness distance.

While no real cameras provide zero (the low-level gips stack doesn't allow it), this was helpful for internal screensharing devices which put 0,0,0 to survive the ideal algorithm.

This should also be useful on OSX where we feed the ideal algorithm fake hardcoded devices. These are hardcoded to 30 fps in Firefox 38, but I suspect OSX can return any framerate, so zero FPS might work better there.

**Comment by alvestrand** [comment]
List poked June 12.

**Comment by alvestrand** [comment]
Closing due to lack of interest.

**Comment by fluffy** [comment]
I do not think this should be closed. It is still not clear how to implement this. Repoening.

**Comment by alvestrand** [comment]
Can you PLEASE respond on the list to my query, and give the argument why this can't be left open for experimentation by implementors?

When I said "lack of interest", I meant *no* responses. Things that people can't be bothered to even start thinking about have no place in a consensus spec.

**Comment by elagerway** [comment]
It doesn't appear as though there is tremendous interest here, we should likely be closing this?

**Comment by ShijunS** [comment]
Agreed that the constraint logics are very complicated, but we managed to implement it in Edge.  I'd not suggest further changes in the area.  Let's give time for web developers to use this and provide feedbacks.

**Comment by elagerway** [comment]
Sent an email to the media capture list with no response, closing.
