### ISSUE TITLE
Need to specify action on constraints that give no value.

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#139]
The action to be taken on constraints { height: {} } needs to be clear from the spec.

Spec currently says it MUST specify a value, but leaves open what happens if you try to call the API with a constraint that doesn't.

**Comment by jan-ivar** [comment]
Right, the spec should say how the UA **MUST** treat input, rarther than what the input **MUST** be.

A related question is what { facingMode: [] } means.

Fwiw, since absence of height/facingMode in user-input is well-defined to mean "don't constrain on height or facingMode", it may be natural to put the above in the same basket. Then there's no need to throw anything.

**Comment by stefhak** [comment]
I'd be happy to leave this to the Editor's discretion.

**Comment by burnburn** [comment]
This is not an editorial issue, but a functionality issue.  Unless someone finds a problem with it, it seems reasonable that specifying a null value for a constraint essentially resets that property to have no constraints from that track.

**Comment by jan-ivar** [comment]
Careful, null and undefined are different. I assume you mean treat { height: {} } and { facingMode: [] } as {}

**Comment by alvestrand** [comment]
We seem to have consensus that empty constraints mean the same thing as omitted constraints.
Good. Then it's an editorial issue to incorporate that.

**Comment by burnburn** [comment]
Addressed with commit 128aadc9acfba0ef1d5e251055d858e0c0c1e6ea
