### ISSUE TITLE
MediaStreamError should not be an interface

### ISSUE THREAD

**Issue by annevk** [w3c/mediacapture-main#162]
Errors in the platform are represented by JavaScript `Error` object subclasses.

**Comment by annevk** [comment]
@domenic

**Comment by domenic** [comment]
There's a note:

> We use MediaStreamError rather than deriving from Error until the situation with adding additional information into an error has been clarified. 

I do think this needs to be resolved before the spec advances though. If nothing else, they can define their own Error subclass using full-on ES spec terminology, similarly to what Web IDL does (but probably less crazily since Web IDL is caught in a mix of ES5 and ES6 worlds).

**Comment by jan-ivar** [comment]
@domenic Thanks, I'm not an editor but I'm sure any pointers to examples of how that should or might look like would be appreciated.

**Comment by domenic** [comment]
@jan-ivar https://people.mozilla.org/~jorendorff/es6-draft.html#sec-nativeerror-object-structure is basically what you want to do. It's templatized on _NativeError_ so just use `MediaStreamError` instead and add a few steps to the constructor specifying how to set the extra properties. (Probably don't add to the .prototype like .message and .name are, those seem like largely legacy...)

You'll probably also want something at the top of such a section saying something like "assume that the rules for [ECMAScript standard built-in objects](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-ecmascript-standard-built-in-objects) are in effect in this section" so that it's clear that e.g. the property descriptor defaults are the same as in ES, `.length` and `.name` are inferred the same way, etc.

**Comment by adam-be** [comment]
@domenic, are you saying that we shouldn't use WebIDL to describe MediaStreamError, but rather do it in prose?

**Comment by domenic** [comment]
Yes, WebIDL does not have the capability to create new Error subclasses.

**Comment by alvestrand** [comment]
Is it kosher to declare a WebIDL object and use prose to say "we are declaring an Error subclass that has the same fields as this WebIDL object"?

Or is it best to avoid WebIDL altogether?

**Comment by domenic** [comment]
Yeah, that doesn't really work, as WebIDL interfaces have entirely different semantics than ES error types do. You might as well use a bulleted list and say "we are declaring an Error subclass that has the same properties as this bulleted list". (But you would of course have to add details on e.g. what the constructor signature is, how/when the properties are defined, etc. like the ES spec does, so that would just be an informative note.)

**Comment by jan-ivar** [comment]
Is it too late to to reconsider putting the failing constraint name in the message...?

**Comment by alvestrand** [comment]
... the last 3 times we discussed putting the failing constraint name in the message, the prospect of forcing users into parsing messages with undefined syntax (or limiting them to giving only this information and nothing else) did not fill people's hearts with joy.
We went through this with SMTP (ended up with error codes + messages, some of which people try to parse with limited success) and IMAP (ended up with a defined syntax for the machine-parseable part of messages). Neither is enjoyable.

**Comment by burnburn** [comment]
This is (finally) addressed via the PRs above, so closing.

**Comment by annevk** [comment]
I don't see how this was addressed actually.

**Comment by dontcallmedom** [comment]
@annevk the changes had not been integrated in the published editors draft when the issue was closed; the editors draft has now been updated: http://w3c.github.io/mediacapture-main/getusermedia.html#error-handling

can you check whether this addresses your comment?

**Comment by annevk** [comment]
Hmm, defining new ECMAScript classes like that does not seem ideal, but okay. Did @domenic review it?

**Comment by burnburn** [comment]
Yes, @domenic was the one who suggested we define ECMAscript classes in that way.  We all agree it is not ideal, but without a way to accomplish this in WebIDL and with our group's goal of moving soon to Candidate Recommendation, the editors would love to be able to call this good for this version of the specification.

**Comment by annevk** [comment]
Sure, but did @domenic review the outcome? If he did I'm okay.

**Comment by burnburn** [comment]
@domenic and @annevk , this is an explicit request for both of you to review http://w3c.github.io/mediacapture-main/getusermedia.html#error-handling as it is now with respect to how errors are defined in the specification.  I will also email both of you pointing to this issue number.  I would like to get a thumbs up from both of you in this thread so we can close this.

**Comment by domenic** [comment]
Yes, this is fine. Maybe one day Web IDL will grow support for custom exceptions. But nobody knows when that will be and this is great and precise for now.

**Comment by annevk** [comment]
Okay, sounds good then.
