### ISSUE TITLE
API to expose the angle of view of a camera

### ISSUE THREAD

**Issue by tobie** [w3c/mediacapture-main#236]
**Use case:** an augmented reality app that would layer labels for points of interest on top of the video stream of the device's camera. In order for the labels to be positioned correctly, it is necessary to know the angle of view of the camera.

**Resources:**
- [Wikipedia article on angle of view](https://en.wikipedia.org/wiki/Angle_of_view),
- Android `Camera.Parameters` [`getHorizontalViewAngle()`](http://developer.android.com/reference/android/hardware/Camera.Parameters.html#getHorizontalViewAngle()) and [`getVerticalViewAngle()`](http://developer.android.com/reference/android/hardware/Camera.Parameters.html#getVerticalViewAngle()) APIs.

**Comment by stefhak** [comment]
I think this is a bad time to introduce new things as we're trying to close the LC process. Could this be done as an extension (e.g. a new Constraint)?

**Comment by anssiko** [comment]
We [minted our own][1] to cater for the same use case. I'd also like to see this feature to be added to the gUM proper in its v.next.

[1]: http://w3c.github.io/mediacapture-depth/#mediatracksettings-dictionary

**Comment by stefhak** [comment]
Closing this issue. While these features are nice, they will have to go into an extension spec or a next version.

**Comment by tobie** [comment]
Is there somewhere to trac use cases and requirements fir a v2?

**Comment by anssiko** [comment]
@stefhak I think monkey patching the main spec in extension specs should not be encouraged since that has known issues. I've been there and done that, and agree with [Anne's summary][1]:

>We should avoid monkey patching (hereafter patching). It has at least these problems:
* A base specification may not be aware of any patches being applied to it and invalidate them.
* Readers of a base specification may not be aware of patches being applied and write code around an incorrect model.
* If patches start getting applied from multiple sources the overall model quickly becomes too hard to see and mistakes start creeping in all over.

GitHub has built-in infrastructure to support working on multiple parallel branches and managing issues per release. For example, Service Workers spec [branched into v1 and Nightly][2] recently and uses [milestones][3] to track v1 and Nightly (aka ED) issues in the same repo. The v1 will advance on the Rec Track while the Nightly will continue accept new features.

Have you considered branching for mediacapture-main v1 so that the ED could again accept new features? You could use GitHub milestones to manage issues that go into each release. This way you could keep all the development in the mediacapture-main repo.

Ping @dontcallmedom. What would be an appropriate channel to discuss this further? The mailing list?
 
[1]: https://annevankesteren.nl/2014/02/monkey-patch
[2]: https://lists.w3.org/Archives/Public/public-webapps/2015JulSep/0368.html
[3]: https://github.com/slightlyoff/ServiceWorker/milestones

**Comment by dontcallmedom** [comment]
@anssiko the mailing list sounds good, but before that, I think it would be useful to disentangle several points that have been made here:
* abstract versioning: what goes in v1, vnext, extension specs (this partially overlaps with the discussion on constraints extensibility)
* expectation settings: where do we document what we want in vnext
* practical versioning: how/where do start work on vnext
* specific extensibility issue (i.e. monkey patching avoidance): do we need to patch v1 so that getSettings can be made extensible by other specs? (avoiding monkey patching doesn't mean everything needs to be done in the core spec)

**Comment by anssiko** [comment]
I agree this is multifaceted. I believe the chairs would be in the best position to take this topic onward (since this is OT for this specific issue now). Here are my thoughts:

* abstract versioning

Process-driven way would be to tie this to the Rec Track, and say that what gets in CR is considered v1. But this is often too late in practice. My hunch is this particular requirement for advancement should be central to the v1/vnext/extension decision:

>* must document how adequate implementation experience will be demonstrated,

* expectation settings

I feel adding a "v2" or "feature request" label to such issues would solve this.

* practical versioning

If in WG's scope, chairs investigate if there are enough editorial resources, interested implementers, otherwise work in WICG or a dedicated CG first.

* specific extensibility issue

More clearly defined extension points would definitely help keep the extensions specs consistent. I kind of like the way how the [SW extensibility section][1]) gives concise and concrete guidance to extension spec authors with boilerplate IDL and prose. This helps keep multiple extension specs consistent among themselves. I feel the Constrainable Pattern section is not as clear in this regard.

[1]: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#extensibility

**Comment by stefhak** [comment]
@anssiko Thanks for bringing this up, you have good points. The chairs will take some time to think about how to move forward with this.

**Comment by anssiko** [comment]
@stefhak Thanks for considering the feedback. I'm happy continue this discussion on a more appropriate venue.

(While the larger issue may be hard to address in the short term, I believe some parts have a reasonable fix, e.g. the expectation setting. Time permitting, this topic might warrant a brief F2F discussion, especially, if the critical mass of the extension specification editors are planning to attend and/or observe the meeting.)
