### ISSUE TITLE
Iframe sandboxing options for gUM

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-main#268]
The fullscreen API has an option for sites to allow iframes to request fullscreen.  We should discuss having that sort of option and what the default would be (allow or deny).

n.b., fullscreen prevents use of the API in an iframe by default

**Comment by martinthomson** [comment]
A simple option here would be to add an "allow-usermedia" tag to [the iframe sandbox attribute](http://www.w3.org/TR/html5/embedded-content-0.html#attr-iframe-sandbox).  That would make this available by default (less breakage), but make it possible to restrict what is possible in the sandbox.

**Comment by stefhak** [comment]
I like that proposal, I think the ability for the site to disallow iframes to access camera and microphone is important.

**Comment by alvestrand** [comment]
Would this mean that "allow-usermedia=no" would disallow iframes' access, while specifying "allow-usermedia=yes" or leaving it off would both allow it?

**Comment by adam-be** [comment]
@alvestrand, from what I've seen it's only the presence of the token, no corresponding value, that activates the feature. But shouldn't it be "disallow-usermedia" to get the behaviour with default on?

**Comment by stefhak** [comment]
@martinthomson any comment to the above?

**Comment by martinthomson** [comment]
I don't know enough about how people use this to know whether to default to on or off.  I think that @adam-be is right about the label form, but the fact that there are no other labels of the form "disallow-*", we would need to be very careful about adding that.

**Comment by adam-be** [comment]
I think the main question here is what the default should be. Then we can figure out how to enforce that; "allow-usermedia" or something else.

As @martinthomson wrote above, default on means less breakage. But it seems that most (read as all) iframe sandbox features are default off and the script opts in.

**Comment by dontcallmedom** [comment]
there are two types of sandboxing:
* [`<iframe sandbox="allow-foo allow-bar">`](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-iframe-sandbox)
* [`<iframe allow-foo>`](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-iframe-allowfullscreen)

The first one has for effect that by default, you get an iframe that has many features cut-off, and get specific features re-enabled via the keywords `allow-foo` and `allow-bar` in my example. The currently recognized features are:  `allow-forms, allow-modals, allow-pointer-lock, allow-popups, allow-popups-to-escape-sandbox, allow-same-origin, allow-scripts, and allow-top-navigation`.

The second one has only been defined for fullscreen at the moment; in that model, fullscreen is disabled by default in any iframe, and can only be enabled specifically by adding that attribute.

While I think it would be useful to think about both getUserMedia and WebRTC impact on the sandbox attribute, I think in this particular case, we're really thinking about the second model, and whether to take the lenient backwards-compatible appraoch (which would require a `disallowusermedia` attribute) or to take the more stringent likely not bw-compatible approach, with an `allowusermedia` attribute.

I personally think the latter is cleaner, but we would need visibility on the deployment reality to determine if that's still an option.

**Comment by alvestrand** [comment]
Den 02. des. 2015 16:10, skrev Dominique Hazael-Massieux:
> there are two types of sandboxing:
> 
>   * |<iframe sandbox="allow-foo allow-bar">|
>     <https://html.spec.whatwg.org/multipage/embedded-content.html#attr-iframe-sandbox>
>   * |<iframe allow-foo>|
>     <https://html.spec.whatwg.org/multipage/embedded-content.html#attr-iframe-allowfullscreen>
> 
> The first one has for effect that by default, you get an iframe that has
> many features cut-off, and get specific features re-enabled via the
> keywords |allow-foo| and |allow-bar| in my example. The currently
> recognized features are: |allow-forms, allow-modals, allow-pointer-lock,
> allow-popups, allow-popups-to-escape-sandbox, allow-same-origin,
> allow-scripts, and allow-top-navigation|.

So if you don't have a sandbox attribute, modals (for instance) are
allowed, but if you have a sandbox attribute with an empty value, modals
are disallowed?

> The second one has only been defined for fullscreen at the moment; in
> that model, fullscreen is disabled by default in any iframe, and can
> only be enabled specifically by adding that attribute.
> 
> While I think it would be useful to think about both getUserMedia and
> WebRTC impact on the sandbox attribute, I think in this particular case,
> we're really thinking about the second model, and whether to take the
> lenient backwards-compatible appraoch (which would require a
> |disallowusermedia| attribute) or to take the more stringent likely not
> bw-compatible approach, with an |allowusermedia| attribute.
> 
> I personally think the latter is cleaner, but we would need visibility
> on the deployment reality to determine if that's still an option.

Seems that people who use the sandbox attribute would care about
restricting the capabilities of the iframe, so would be happy (?) to see
usermedia starting out as default off, while people who don't use it
would perhaps want the default (with no sandbox attribute) to be the
status quo - that it's allowed on.

Would that be the best of all possible worlds?

**Comment by dontcallmedom** [comment]
> So if you don't have a sandbox attribute, modals (for instance) are allowed, but if you have a sandbox attribute with an empty value, modals are disallowed?

Yes.

> Seems that people who use the sandbox attribute would care about restricting the capabilities of the iframe, so would be happy (?) to see usermedia starting out as default off, while people who don't use it would perhaps want the default (with no sandbox attribute) to be the status quo - that it's allowed on. Would that be the best of all possible worlds?

I think making getUserMedia (and likely, WebRTC) disabled by default and reenabled by opt-in in a sandboxed iframe would make sense. But I don't think it's sufficient or a "best of all possible" solution.

The problem with `<iframe sandbox>` is that it forces you into a very constrained iframe, and the list of constraints on this type of iframes can grow over time, so you have to keep adding "allow-foo" keywords if you were only interested in disabling a specific feature.

My understanding of the case we're trying to address is to make getUserMedia an independent toggle; i.e. an iframe could have or not have access to getUserMedia independently of whether that iframe is sandboxed.

Looking at at the usual suspects for iframes, ads, I think most developers would NOT want ads to have access to getUserMedia, and most legitimates ads should NOT need it, but I don't think most developers would want or would be allowed to serve ads from `<iframe sandbox>`.

There seemed to have been a long discussion in [webappsec on the topic back in February](https://lists.w3.org/Archives/Public/public-webappsec/2015Feb/thread.html#msg225); that's probably exploring as well (or maybe more simply, get some input from webappsec on this?)

**Comment by adam-be** [comment]
>>Seems that people who use the sandbox attribute would care about restricting the capabilities of the iframe, so would be happy (?) to see usermedia starting out as default off, while people who don't use it would perhaps want the default (with no sandbox attribute) to be the status quo - that it's allowed on. Would that be the best of all possible worlds?

>I think making getUserMedia (and likely, WebRTC) disabled by default and reenabled by opt-in in a sandboxed iframe would make sense. But I don't think it's sufficient or a "best of all possible" solution.

From @alvestrand's description above about people that use the sandbox attribute and those who don't, is seems that the following would fit.

* no sandbox attribute: enabled (works as before)
* sandbox attribute without "allow-usermedia": disabled
* sandbox attribute with "allow-usermedia": enabled

**Comment by dontcallmedom** [comment]
It would fit the toggle/untoggle usermedia, but it would not fit the atomic aspect of it: the only way you can disable getUserMedia in iframe then requires to use the sandboxed model of iframes, which is way more restrictive than e.g. most ads providers are likely to accept.

**Comment by adam-be** [comment]
Taking the rest of @dontcallmedom's input into consideration; especially (correct me if I've got this wrong Dom):

* Add creators don't want to have their ads in sandboxed iframes (a problem for the site owner since the advertisers won't pay for premium in this case [1])
* User media default on means that ads (in iframes) on existing pages, that aren't updated with restrictions, can start using it in the future

I think we're best of with ```<iframe allowusermedia>``` (= default off)

[1] https://lists.w3.org/Archives/Public/public-webappsec/2015Feb/thread.html#msg225

**Comment by alvestrand** [comment]
We should take this to the list .... I can't find an example of an ad that's presented in an iframe. It's been touted as one of the main reasons for sandboxing, but I can't find a live example.

**Comment by adam-be** [comment]
Let's continue on the list to make this discussion more visible.

https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0008.html

**Comment by stefhak** [comment]
@alvestrand found a few iframe ads at http://www.idg.se/

**Comment by alvestrand** [comment]
Adam is working on a PR for this - based on an "allowusermedia" IDL and content attribute.

**Comment by adam-be** [comment]
Proposed fix #313

**Comment by stefhak** [comment]
Closed, #313 addressed this one.

**Comment by foolip** [comment]
This came up in https://github.com/whatwg/html/pull/1492.

Per some ad-hoc testing in https://github.com/whatwg/html/pull/1492#issuecomment-230443018 it looks like `getUserMedia()` is currently allowed in iframes, and it's quite possible that it's too late to change that. Does anyone have any data on the prevalence of `getUserMedia()` requests in iframes, to get an idea about the risk?

**Comment by upsuper** [comment]
I believe fullscreen is made that way because it preexists sandbox for some impl (which seems to be Gecko), and later other impls adopted that. IIRC, Gecko had a plan about converting `allowfullscreen` attribute to a sandbox flag, but never made it. (I failed to find that, though)

Given this, I suppose `allowfullscreen` is just an exception which we do not want to have any follower. New things should all go to sandbox rather than adding another `allowfullscreen`-like attribute.

Some reasons why I think we should prefer the sandbox way:

1. Using attribute makes logic unnecessarily more complicated. e.g. how should the new attribute interact with the sandbox mechanism? The logic was broken for fullscreen in the spec, and now we are going to completely decouple them.
2. Adding as a sandbox token allows external specs to make use of it. e.g. CSP spec reuses tokens of `sandbox` attribute to control the ability of even top level document.

**Comment by stefhak** [comment]
I'm re-opening this issue as we seem to have some new data. 
Earlier (https://github.com/w3c/mediacapture-main/issues/268#issuecomment-161337256) we concluded sandboxing won't fly, and went for an `allowfullscreen`-like attribute. Maybe this has changed (need more investigation).

For breaking apps with the introduction of `allowusermedia`, there was some discussion at https://lists.w3.org/Archives/Public/public-media-capture/2016Feb/0024.html and https://lists.w3.org/Archives/Public/public-media-capture/2016Feb/0029.html.

**Comment by upsuper** [comment]
It seems the other reason for using `allowfullscreen` rather than a sandbox token was that, roc argued fullscreen makes page inside iframe able to overlay its host, so it should be disabled by default.

That probably makes sense (actually I don't think so, because pages inside non-sandboxed iframe can use popup to overlay its host visually, no?). But anyway that argument doesn't apply to gUM either.

**Comment by upsuper** [comment]
I don't understand why sandbox would be too restrictive for ads? How can a cross-origin ad iframe know whether it is in a sandbox if it is allowed to do everything it is supposed to do by sandbox?

**Comment by foolip** [comment]
Thanks for re-opening, @stefhak!

I think the priority here is to first determine if all engines currently allow `getUserMedia()` calls from inside iframes. Chromium does as long as it's a [secure context](https://w3c.github.io/webappsec-secure-contexts/), @upsuper can probably say exactly what Gecko does, and I don't know who to ask for Edge and WebKit. Anyone?

**Comment by upsuper** [comment]
As far as I can see, Gecko is more generous than Chrome that, gUM is even allowed in a `<iframe>` inside a data-scheme document.

It seems WebKit doesn't support gUM yet, so it's not relevant.

**Comment by ShijunS** [comment]
@foolip, Edge also allows getUserMedia() calls from inside iframes.

**Comment by stefhak** [comment]
@foolip while I agree that what current implementations do is important (as is data on how many applications that would break if they change), we also need to consider what makes sense to require in a specification.
`allowusermedia` was discussed quite a bit before being added to the spec (I provided a couple of links in https://github.com/w3c/mediacapture-main/issues/268#issuecomment-230467434). 
One reason for it was the discussion we had on the permission prompt UI, which basically concluded that the iframe _and_ the top-level origin should be presented to the user, and then it (to me at least) makes sense that the embedding page can control whether or not the `iframe` can request to use microphone and camera (and thus present a prompt containing the embedding page's origin).
A piece of the puzzle was also a discussion on `iframe` permission scoping: https://docs.google.com/document/d/1iaocsSuVrU11FFzZwy7EnJNOwxhAHMroWSOEERw5hO0/edit?pref=2&pli=1
@dontcallmedom can you elaborate why we decided not to make `allowusermedia` a sandboxing attribute?

**Comment by dontcallmedom** [comment]
As described [above](https://github.com/w3c/mediacapture-main/issues/268#issuecomment-161580967) (which itself was a refinement of [another earlier comment](https://github.com/w3c/mediacapture-main/issues/268#issuecomment-161337256), the sandbox model is so restrictive by default (and with a growing & unbounded set of restrictions) that it is unlikely to be used; since using `getUserMedia` from an iframe from a different origin ought to be the exception rather than the norm, the model where it always has to be explicitly enabled seems a better match and to bring better protection to the user.

Now if current usage doesn't allow that change, it is reasonable to reconsider that approach; but it would be useful to have more details on what metrics tell us (if we have any)

**Comment by upsuper** [comment]
> the sandbox model is so restrictive by default (and with a growing & unbounded set of restrictions) that it is unlikely to be used

Sandbox via iframe has a use count of 0.6% of sampled pages from Chrome's stats. Why do you think it is unlikely to be used? (There is no data for how many pages have a cross-origin iframe, though)

The sandbox model which has new potentially dangerous feature disabled by default is something we hope people to use for their cross-origin iframes in general, right?

And by making this feature disabled by default for even non-sandbox, aren't you just making the normal model be aligned with the sandbox model that has a growing and unbounded set of restrictions which you are disapproving?

> using `getUserMedia` from an iframe from a different origin ought to be the exception rather than the norm

This actually applies to many of other sandbox flags, including pointerlock, top navigation, modals, and probably even popups.

With time goes by, people may find new ways to escape from restrictions. By making restrictions a flag in sandbox, spec and impls are able to handle them altogether, rather than fixing each individual attributes.

Also without sandbox, pages can escape from this restriction via a top navigation or popup.

> Now if current usage doesn't allow that change, it is reasonable to reconsider that approach; but it would be useful to have more details on what metrics tell us (if we have any)

TBH, based on Chrome's stats, I don't think the usage would really be a blocker. (GetUserMediaInsecureOriginIframe <= 0.0001%, GetUserMediaSecureOriginIframe <= 0.0001%, so combined at most 0.0002%)

**Comment by dontcallmedom** [comment]
> The sandbox model which has new potentially dangerous feature disabled by default is something we hope people to use for their cross-origin iframes in general, right?
>
> And by making this feature disabled by default for even non-sandbox, aren't you just making the normal model be aligned with the sandbox model that has a growing and unbounded set of restrictions which you are disapproving?

I'm not disapproving of the growing unbounded set of restrictions; I'm saying that the fact that by opting in to sandbox, you're opting in to a growing unbounded set of restrictions makes it less likely people will be opting in. I prefer the model where the default is right.

> This actually applies to many of other sandbox flags, including pointerlock, top navigation, modals, and probably even popups.

OK; if this is the direction where the overall platform is going toward, it probably does not make much sense to make `getUserMedia` an exception. Since I suspect there are many more cross-origin iframes than there are sandboxed iframes, I don't think that's great, but I agree there is value in consistency, especially noting your other remark:
> Also without sandbox, pages can escape from this restriction via a top navigation or popup.

**Comment by foolip** [comment]
> TBH, based on Chrome's stats, I don't think the usage would really be a blocker. (GetUserMediaInsecureOriginIframe <= 0.0001%, GetUserMediaSecureOriginIframe <= 0.0001%, so combined at most 0.0002%)

You can't tell from the name of these counters, but these are only counting cross-origin iframes. AFAICT, there's no metric (in Blink) that just checks how often gUM is used in any iframe.

**Comment by stefhak** [comment]
>You can't tell from the name of these counters, but these are only counting cross-origin iframes. AFAICT, there's no metric (in Blink) that just checks how often gUM is used in any iframe.

The interesting metric is the cross-origin one. Same-origin iframes would always be allowed to do gUM - `allowusermedia` only makes a difference for cross-origin ones.

**Comment by upsuper** [comment]
> The interesting metric is the cross-origin one. Same-origin iframes would always be allowed to do gUM - `allowusermedia` only makes a difference for cross-origin ones.

That would make things more confusing... I believe it doesn't work this way in the current spec anyway, because fullscreen is restricted by default even for same-origin iframes, and `allowusermedia` shares the same algorithm there.

**Comment by foolip** [comment]
@upsuper is right, `allowusermedia` is required for iframes of any origin, both before and after the changes in https://github.com/whatwg/html/commit/9f6b91cb14a0f497ee5b3e7118ee65e687eaea78.

This matches how `allowfullscreen` works, and I have just verified that both Chrome and Firefox in fact do require the attribute to be present even for same-origin iframes.

**Comment by dontcallmedom** [comment]
what's the reasoning behind restricting usage of fullscreen in same-origin iframes?

**Comment by upsuper** [comment]
Hmmm, I guess two reasons:

1. same-origin doesn't mean you can always know what the page would be doing
2. it is just designed that way, because it is simplier and doesn't affect security

**Comment by foolip** [comment]
I see no discussion of origins in https://github.com/whatwg/html/commit/52a28a23a8e7e5a37ec6793d338a50d9080ab189 or https://www.w3.org/Bugs/Public/show_bug.cgi?id=18840 so it's possible that nobody has thought about it, it's just simpler to always require the attribute. @annevk?

**Comment by stefhak** [comment]
Aha, that would be a change for ´allowusermedia´. We've earlier concluded there is no point in requiring it for same-origin iframes.
But to be put in perspective: this particular discussion only (perhaps badly chosen word, it is important) has bearing on the amount of apps we would possibly be breaking, not on the basic design (`allowusermedia` for iframes) per se.

**Comment by annevk** [comment]
@foolip maybe @rocallahan remembers why `allowfullscreen` is required for same-origin `<iframe>`s, I don't.

**Comment by rocallahan** [comment]
I don't remember anyone suggesting we carve out an exception for same-origin `<iframe>`s, so it was probably never considered.

Carving out such exceptions adds complexity. Is there a good reason to do it? Adding `allow` attributes doesn't seem like much of a burden to me.

**Comment by alvestrand** [comment]
The counter for getUserMedia in an iframe is here:

https://www.chromestatus.com/metrics/feature/timeline/popularity/1145

When we previously discussed this, the sentiment was "usage (of feature without a sandbox flag) is low enough, but if we want to kill it, we'd better kill it fast".

I still think that's a good idea.

And yes, we discussed same-origin vs other-origin Iframes, and decided to treat them differently.

**Comment by foolip** [comment]
Given that the document in a same-origin iframe could just add the attribute to the iframe itself, it does seem a bit pointless to require the attribute in that case. If that change were made to HTML then the move to require the `allowusermedia` attribute might work out. https://www.chromestatus.com/metrics/feature/timeline/popularity/1145 measures cross-origin iframes only, and that then becomes the relevant metric.

@alvestrand, are you interested in trying this change in Blink?

I have a lingering doubt that things still aren't going to be very consistent. I checked how Geolocation works, because it also has permission prompts. There, at least Chrome allows requests from cross-origin iframes and shows UI using the iframe's origin. Notifications is another API with an upfront permission prompt. Should we try to get the same story for all APIs with a similar model, and would that mean lots of new allow* attributes?

**Comment by foolip** [comment]
Hmm, it strikes me that having both an allow* attribute, [permission delegation](https://noncombatant.github.io/permission-delegation-api/) and a permissions UI that could handle requests from cross-origin iframes might end up fairly complicated.

This issue is older than https://noncombatant.github.io/permission-delegation-api/, so is there any chance that permission delegation could be the *only* way for cross-origin iframes to use gUM? https://github.com/noncombatant/permission-delegation-api/issues/21 talk about the interaction and it sounds like @raymeskhoury considers these orthogonal concerns, but in a case where we don't yet have the allow* attribute shipping I wonder if it's really a good mix.

**Comment by stefhak** [comment]
@foolip as I may have mentioned, one thing that was on the radar when we did the design was https://docs.google.com/document/d/1iaocsSuVrU11FFzZwy7EnJNOwxhAHMroWSOEERw5hO0/edit?pref=2&pli=1. That document proposes that only the top-level origin would be shown in any permission request UI (even if the actual gUM call is in an iframe of a different origin). It sort of makes sense to me, but then you really need explicit permission delegation (`allowusermedia`).

**Comment by foolip** [comment]
FWIW, we also don't know yet if allowfoo attributes will be a common pattern or if it will only ever be used for Fullscreen. @raymeskhoury, https://docs.google.com/document/d/1iaocsSuVrU11FFzZwy7EnJNOwxhAHMroWSOEERw5hO0/edit?pref=2&pli=1 says "requires delegation" as the new behavior for mic/camera, so I guess that's still what you're hoping for?

**Comment by alvestrand** [comment]
Current status seems to be "no clear direction", which translates to action "no change to spec".

**Comment by foolip** [comment]
Ping @raymeskhoury?

**Comment by stefhak** [comment]
There has been some discussion over at https://github.com/WICG/feature-policy/issues/11. The [Permission Delegation](https://noncombatant.github.io/permission-delegation-api/#delegation-via-the-declarative-api) API (which seems usable) is planned to be folded into Feature-Policy. 

However, the formal status, as well as the maturity, of Feature-Policy seems a bit unclear to me, so personally I think we should keep ```allowusermedia``` - at least until we know more about stability, maturity and formal status of Feature-Policy.

**Comment by foolip** [comment]
I suppose the first engine that tries to disallow `getUserMedia()` in (cross-origin?) iframes will have to decide on the opt-in mechanism, and it'll depend on whether it already has the Permission Delegation API or something similar at that point.

Is it acceptable that `allowusermedia` is required even on same-origin iframes? If it is, then I suppose there is nothing to do here except to wait and see who moves first, and for everyone else to then do it the same way.

**Comment by alvestrand** [comment]
Is there an attack that can be facilitated by "allowusermedia" defaulting to "on" for same-origin iframes?
If "yes", I'd want to stick with current language; if "no", I'd be willing to add "with a different origin" in there so that same-origin iframes don't need it.

(The case I could think of is where a same-origin iframe is used to include and isolate content from untrusted sites such as ad networks without another level of iframe to isolate it - does this make sense?)

**Comment by stefhak** [comment]
In any case, specification wise we seem to be broken right now. Permission
API says, that only iframes with allowusermedia are allowed to request
access (regardless of same origin or not) and goes on to say that Media
Capture and Streams defines allowusermedia, but it does not.

On Thu, Aug 11, 2016 at 6:10 PM, Harald Alvestrand <notifications@github.com

**Comment by foolip** [comment]
@alvestrand, I think as long as the condition for when it's not required matches exactly the cases where the iframe could reach out and add the attribute itself, there can be no security issue. So a case where example.com embeds itself in a sandbox would still need to require the `allowusermedia` attribute.

The thing is that the change would have to be in HTML's algorithm, and would then apply to `allowfullscreen` as well. I'd be fine with just deferring until an implementer comes along and wants to disable `getUserMedia` in iframes by default, which will flush out all of the other issues.

@stefhak, I've filed https://github.com/w3c/permissions/issues/121 to sort out the Permission API wording.

**Comment by raymeskhoury** [comment]
Hey sorry for the delay @foolip 

How quickly do you need to add an attribute like this? "Feature policy" will be the generic way to do this: https://wicg.github.io/feature-policy/

It will allow certain features to be disabled by default in embedded contexts and re-enabled through the use of an attribute (or meta tag or header).

**Comment by foolip** [comment]
@raymeskhoury, I'm not one of the relevant implementers, but I *think* what will force this issue is changing `getUserMedia()` to reject in iframes my default, necessitating *some* way to delegate. Nobody on this thread has declared any imminent plan to work on it in any engine.

With feature policy + delegation, I guess it would be `<iframe permissions="camera microphone">` instead of `<iframe allowusermedia>`?

**Comment by stefhak** [comment]
The mediacapture-main document (in CR) currently just refers to a ```user media enabled flag``` and says that the details of how to control that flag is beyond the scope of the spec. So I think that from this spec ```allowusermedia``` as specced for iframes in https://html.spec.whatwg.org/multipage/embedded-content.html or something from https://wicg.github.io/feature-policy/ would both be OK.

**Comment by stefhak** [comment]
Given that

- this Issue was reopened due to the question if it would be too late to introduce "active delegation needed" (https://github.com/w3c/mediacapture-main/issues/268#issuecomment-230457411) and the discussion has since moved to be about the right way for the web author to indicate delegation

and that

- this spec leaves it open how the web author would indicate delegation 

would anyone think it is a bad idea to (re-)close this Issue?

**Comment by annevk** [comment]
I think we want to know if what is in HTML will be implemented or needs to change.

**Comment by raymeskhoury** [comment]
@foolip 

> I think what will force this issue is changing getUserMedia() to reject in iframes my default, necessitating some way to delegate

Yep, I agree. So I was hoping that we could hold off doing that until we have Feature Policy more solidified. We're in a hurry to do that now anyway :)

> With feature policy + delegation, I guess it would be <iframe permissions="camera microphone"> instead of <iframe allowusermedia>?

Something like that, the exact syntax is tbd.

**Comment by stefhak** [comment]
@annevk I agree, somehow and somewhere we (the community) needs to agree on how to do permission delegation. To me it is unclear whether it will be ```allowXXX``` or what is being defined in feature-policy (or something else).

**Comment by annevk** [comment]
I suspect something like feature-policy is the way to go, but that will take some time to reach consensus across browsers and community, settle on syntax, figure out edge cases, etc. (And that too will need to be integrated with HTML, which I guess brings us back to my earlier comment. 😊)

**Comment by alvestrand** [comment]
We seem to have a flag in the WHATWG version of HTML (allowusermedia). The policy feature work will also set or unset the flag. We have specified the handle they're going to manipulate.
Nothing more to be done here.

**Comment by annevk** [comment]
@alvestrand I'm not sure what you mean by "seem to have a flag". I don't think that's true. There's an algorithm if you want to use an attribute. And if you want to use that then you need to upstream that attribute.

I guess you wouldn't use the permission delegation then as discussed upthread.

**Comment by raymeskhoury** [comment]
I think @alvestrand is referring to: https://html.spec.whatwg.org/multipage/embedded-content.html#the-iframe-element:attr-iframe-allowusermedia

@alvestrand just a heads-up that we're currently working on adding allowusermedia as a [Feature Policy](https://docs.google.com/document/d/1k0Ua-ZWlM_PsFCFdLMa8kaVTo32PeNZ4G7FFHqpFx4E/edit) flag as well.

**Comment by alvestrand** [comment]
@raymeskhoury Yes, that's the one I was thinking of. I certainly hope you end up with a consistent set of feature identifiers in all those places.

**Comment by annevk** [comment]
That is all fine and well, but that does not work without https://w3c.github.io/mediacapture-main/ actually invoking the "allowed to use" algorithm defined there.

**Comment by alvestrand** [comment]
@annevk can you file a bug on getusermedia telling us what to replace the text "If the current [HTML51] Document's user media enabled flag is unset, return a promise rejected with a DOMException object whose name attribute has the value SecurityError." with?

**Comment by annevk** [comment]
Isn't this that bug?

**Comment by alvestrand** [comment]
@annevk I thought we had solved it, and you're telling me the solution is wrong. Thought it would be simpler to open a new bug, but since you ask...

Reopened. Can you suggest how we should phrase it?

**Comment by annevk** [comment]
I think you need to make the following changes.

1. Remove "All Documents have a user media enabled flag. This specification does not detail how or when this flag is set."
2. You need to rephrase "If the current [HTML51] Document's user media enabled flag is unset" somehow. I don't understand what "current Document" means. But once you have a handle on a document, you want to say something like "If _document_ is [allowed to use](https://html.spec.whatwg.org/multipage/embedded-content.html#allowed-to-use) the feature indicated by attribute name `allowusermedia`, then ..."

See https://fullscreen.spec.whatwg.org/#fullscreen-element-ready-check for an example.

**Comment by stefhak** [comment]
@annevk I've started to draft a PR to do what you propose in https://github.com/w3c/mediacapture-main/issues/268#issuecomment-261883257, and have one question. In the "[fullscreen element ready check](https://fullscreen.spec.whatwg.org/#fullscreen-element-ready-check) there is a check whether the `allowfullscreen` attribute is set, but should there not be some kind of chain here? I mean if an iframe without `allowfullscreen` creates an iframe with `allowfullscreen`, should the later really be allowed to use full screen?

**Comment by annevk** [comment]
The allowed to use algorithm does the recursion, no?

Now, there are some changes underway to rather than have a dynamic check, make a snapshot when the browsing context is created. @zcorpan is leading that in https://github.com/whatwg/html/pull/2195 and https://github.com/whatwg/html/pull/2217.

If `allowusermedia` is not implemented yet, it should be snapshotted like we will do for payments and not be dynamic like we do for fullscreen. @zcorpan can update the PRs to account for that if indeed it's not implemented yet.

Hope this helps.

**Comment by stefhak** [comment]
Thanks. `allowed to use` algorithm does the recursion indeed.
I personally agree allowusermedia should be snapshotted.

**Comment by stefhak** [comment]
Can we close this one now that #427 is merged?

**Comment by alvestrand** [comment]
I think so. Closing.

**Comment by annevk** [comment]
Yeah, seems pretty confusing to reference conflicting HTML standards, but if that's how you want to make progress, so be it I guess.

**Comment by alvestrand** [comment]
Yeah, moving all the pointers to point to WHATWG is not an option, so conflicting pointers it is.

**Comment by stefhak** [comment]
@annevk regarding https://github.com/w3c/mediacapture-main/issues/268#issuecomment-273804165: of course any advice is welcome. https://w3c.github.io/browser-payment-api/#dependencies says html51 defines "allowed to use" and "allowpaymentrequest"; however I can't find them being defined in https://www.w3.org/TR/html51/ (though I must admit I find it hard search in that document) and trying to look into the latest editors draft takes me to html5.2 (and it is equally hard to search in that doc).

**Comment by annevk** [comment]
My advice is not reference that document as it repeatedly causes confusion for those implementing (who need to ignore it). See https://annevankesteren.nl/2016/01/film-at-11 for more detailed rationale.

**Comment by stefhak** [comment]
Thanks (though I'm pretty sure we're supposed to be referencing W3C specs when we can).
