### ISSUE TITLE
Replace ErrorEvent with ErrorEvent in html

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#335]
There's already an `ErrorEvent` [in the html spec](https://html.spec.whatwg.org/multipage/webappapis.html#the-errorevent-interface), and we should use that instead of defining our own. This is what all the other specs are doing, I've been informed.

**Comment by foolip** [comment]
Do all of the attributes of `ErrorEvent` make sense for your case? Which other specs use it?

**Comment by alvestrand** [comment]
The only thing we need from ErrorEvent to match previous behavior is the "message" field.

The ErrorEvent also has a wonderful "any"-typed "error" field - which means that it's legal to return absolutely everything. Are you sure this is really appropriate?

**Comment by jan-ivar** [comment]
We need the `message` field *and* the `name` field. See https://github.com/w3c/mediacapture-main/issues/336#issue-144976523.

**Comment by alvestrand** [comment]
Yep, the "name" field is not part of the ErrorEvent; I assumed that it was inherited from Error, but now when taking a look I see that Error has a "type" field, not a "name" field.
So why does "ErrorEvent.name" return anything at all?

**Comment by jan-ivar** [comment]
I think you mean *Event* has a `type` field.

> So why does "ErrorEvent.name" return anything at all?

TIL that Error *does* in fact [have a name field](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name#Throwing_a_custom_error), just not a constructor for it. Who knew.

Even so, by going with the html one, we can throw whatever, be `Error`, `TypeError` etc. or `DOMException`, we're not limited.

**Comment by stefhak** [comment]
FWIW, webrtc-pc references the html ```ErrorEvent```.

**Comment by foolip** [comment]
So is there any spec other than HTML that uses `ErrorEvent`? I ask because it honestly seems like a strange thing to do, given how specific it is to reporting errors in scripts, with line/column information and everything.

If it's only used for "Any error occured from the data channel" then maybe a RTCDataChannelErrorEvent would be a better fit?

**Comment by jan-ivar** [comment]
@foolip good point. I shouldn't have taken that at face value. The only other use I found was in [workers](https://www.w3.org/TR/service-workers/#service-worker-container-error-event).

Agree file and line number don't make sense with events fired from built-in code. Even an error property may be a bad idea, I see now, because it encourages this pattern (which is why I wanted one):

```js
var rec = new MediaRecorder(stream);
rec.start();
var stopped = new Promise((resolve, reject) => {
  rec.onstop = resolve;
  rec.onerror = event => reject(event.error));
});
```
instead of being forced to do something like:
```js
var stopped = new Promise((resolve, reject) => {
  rec.onstop = resolve;
  rec.onerror = event => reject(new DOMException(event.message, event.name));
});
```
The latter looks ugly, but we get file and line number (and stack) pointing to the `onerror` line, which may be extremely helpful in long promise-chains, whereas in the former case we get nothing.

> If it's only used for "Any error occured from the data channel" then maybe a RTCDataChannelErrorEvent would be a better fit?

Don't forget https://github.com/w3c/mediacapture-record/issues/42. Seems common to expect to find someplace shared. Pity `ErrorEvent` may not be it.

**Comment by jan-ivar** [comment]
s/common/common enough/

**Comment by foolip** [comment]
The Service Workers case uses HTML's [report the error](https://html.spec.whatwg.org/multipage/webappapis.html#report-the-error) algorithm to report errors in scripts, so that usage looks like a straightforward extension to what HTML does.

> The latter looks ugly, but we get file and line number (and stack) pointing to the `onerror` line, which may be extremely helpful in long promise-chains, whereas in the former case we get nothing.

That doesn't sound right. `ErrorEvent` as used in HTML can report the place where a parse error happens. In some ad-hoc testing I wasn't able to see any runtime errors reported using `ErrorEvent`. Having it report where the error event handler was registered (or something like that) sounds strange, are you sure that can be done?

The situation you have here looks quite a look like error events on media elements, which use a simple error event and a `MediaError` object. I think that here too, the error can happen at any time and isn't connected to any specific API call where a promise could be rejected?

**Comment by jan-ivar** [comment]
@foolip, you convinced me already. I'm not arguing for using html `ErrorEvent` anymore. Closing this and opening a new issue to argue for removing the `Error` member: https://github.com/w3c/mediacapture-main/issues/337

**Comment by foolip** [comment]
OK, sorry I didn't catch on :)
