### ISSUE TITLE
Error member in an Event for runtime-errors is a bad idea

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#337]
...because the `Error`'s file, line number and stack will always be empty.

Not only is this wasteful, it fools people into thinking it *might* have useful information that they better log or forward, taking the place of more useful information.

Here's an [example](https://jsfiddle.net/tmwLxjLy/) (yes I like promises, and yes the example is mediaRecorder,  but it has the same event):

```js
var rec = new MediaRecorder(stream);
rec.start();
var stopped = new Promise((resolve, reject) => {
  rec.onstop = resolve;
  rec.onerror = event => reject(event.error));
});
```
`stopped` resolves when the recording ends, or rejects at the first runtime error, whichever happens first.

But when a `SecurityError` error later shows up in my console, there's no file or line number. In a larger program, this would suck.

If we replace `.error` with `.name` and `.message` then I know there's no deeper information to forward:

    rec.onerror = event => reject(new DOMException(event.message, event.name));

And now the `SecurityError` points to this call site, which tells me it's a runtime error in `rec`.

I think this is a general problem with all runtime-error events.

**Comment by foolip** [comment]
Just to make sure we're all on the same page, which event and error interfaces are we talking about here? It's HTML `ErrorEvent` that has `filename`, `lineno` and `colno` members.

https://w3c.github.io/mediacapture-main/#errorevent will have to be removed because its definition conflicts with HTML's `ErrorEvent`, but what should be added instead?

**Comment by alvestrand** [comment]
The only place I can see that uses the ErrorEvent interface is the "ended" event.

One possible solution is making the "ended" event a simple event. Has anyone implemented the error part here?

**Comment by jan-ivar** [comment]
@foolip yes I'm talking about https://w3c.github.io/mediacapture-main/#errorevent and also http://w3c.github.io/mediacapture-record/MediaRecorder.html#errorevent which is identical (I agree they can't all have the same name.

I was referring to the `stack` (and in Firefox `fileName` and `lineNumber`) often found on [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) for debugging purposes.

**Comment by jan-ivar** [comment]
@alvestrand Firefox doesn't implement `onended` yet fwiw. When would the error be used? I find no mention of it firing with an error in any spec.

**Comment by foolip** [comment]
It seems strange that the `ended` event is an error at all, presumably there are ways for the capture to end that aren't because of something unexpected happening? Maybe there should be separate `ended` and `error` events? And maybe `overconstrained` should be merged into a more generic `error` event?

I'm just throwing out ideas here.

**Comment by alvestrand** [comment]
I remember long-ago discussions about the "ended" event, where people said that they wanted to know the difference between "ended, no error" and "ended, something bad happened". The example given was, I think, the track ending because of a track.stop() or a remote orderly shutdown vs a track ending because of a camera being yanked out of the computer.

We put the error in there for that case, intending it to be nullable. And then we forgot about it until now, I think.

**Comment by foolip** [comment]
FWIW, `HTMLMediaElement` has separate events for `error` and `ended`. Both are simple events, and errors are reported via a `MediaError` object on `mediaElement.error`. It's actually not great, but with errors that aren't associated with any API call it has to be either that or a special kind of event like what you have...

**Comment by jan-ivar** [comment]
> The example given was, I think, the track ending because of a track.stop() or a remote orderly shutdown vs a track ending because of a camera being yanked out of the computer.

@alvestrand thanks for reminding me the event param is nullable, and usually null. I should close this and open the exact same issue on mediarecorder instead.

I'm trying to remember the use for error as well. I doubt however that any bits on the wire exist to communicate such failures to the other side, and nothing seems to have been spec'ed, so I'm all for ripping out this error in the mediacapture case and let whatever spec needs it reintroduce it.

**Comment by alvestrand** [comment]
Submitted #338 to suggest removing the information (this flags to the list that this is suggested).
