### ISSUE TITLE
IFrame access control makes problems for [CEReactions] introduction

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#353]
As exemplified in #344, the fact that we have pieces of our spec update pieces of the HTML spec makes it hard to maintain the HTML spec when the editors need to do sweeping changes like the introduction of [CEReactions].

Possible alternatives are:
- Patch our spec whenever it's needed
- Move the extension fo the HTMLIframeElement to the HTML spec

The latter alternative would also allow central maintenance of the pattern of "here's how access powerful features get passed into iframes", if that's desirable.

Tagging @domenic and @adam-be for their input.

**Comment by domenic** [comment]
I'd be happy to help with the process of moving the HTMLIFrameElement extension into the HTML spec. This generally is beneficial, as it gives authors and implementers of tools like conformance checkers a more centralized view of relevant content attributes. (Implementers of browsers are not really affected, as if they're implementing media capture, they'll see this spec.) We're working on similar moves for a few other specs which have to patch attributes onto HTML elements, like referrer policy and subresource integrity.

How I would envision this working, concretely, is that the definition of "allowed to access user media" moves to the intro section of "Obtaining local multimedia content", where it would say something like

> Every browsing context has an allowed to access user media flag. This specification does not detail how such or when this flag is set.

or similar.

Then, HTML can define that all non-nested browsing contexts have the flag set, and can define the the iframe content attribute and IDL attribute to control the flag for nested browsing contexts.

How does this sound? I'd be happy to work on a pull request for HTML you could review to see the impact. I think this is a much nicer modularity boundary than the current approach, separating the host environment stuff (like extensions to HTMLIFrameElement and the content attribute) from the core media-capture--related concepts (like "allowed to access user media").

**Comment by stefhak** [comment]
This sounds reasonable, but is there a time line for when we could expect this to propagate into HTML? Or would we reference something immature while trying to more to Rec.?

**Comment by domenic** [comment]
I could have it in HTML for you by Wednesday at the latest.

**Comment by stefhak** [comment]
Awesome! However, before we do that we should get some more comments saying this is the right thing to do.

**Comment by domenic** [comment]
Who are we waiting for to comment on this?

**Comment by alvestrand** [comment]
@adam-be as author of previous text. Would be nice to get @martinthomson and @pthatcherg too.
Today's not likely to be a workday in Sweden, though.
@domenic do you have a PR in the whatwg repo we can compare to?

**Comment by martinthomson** [comment]
[This](https://github.com/w3c/mediacapture-main/issues/353#issuecomment-215851094) looks like a reasonable plan to me.

**Comment by domenic** [comment]
I've put up a HTML PR for you all to review: https://github.com/whatwg/html/pull/1211

As noted there, the proposal is very slightly different from my https://github.com/w3c/mediacapture-main/issues/353#issuecomment-215851094 since in the course of working on this I discovered that `allowfullscreen` is done slightly differently. The revised proposal for what this spec would do is:

> It expects the current [allowed to access user media](https://w3c.github.io/mediacapture-main/#dfn-allowed-to-access-user-media) to become a "user media enabled flag", which exists on Documents instead of browsing contexts, and has an ID of `dfn-user-media-enabled-flag`. This is done to parallel Fullscreen's [fullscreen enabled flag](https://fullscreen.spec.whatwg.org/#fullscreen-enabled-flag).

(ID and naming are of course up to you all; I just thought paralleling fullscreen might make sense. The only really important thing is that it's on Documents instead of browsing contexts.)

**Comment by alvestrand** [comment]
What's the observable difference?
I see that the flag on an iframe is still called "allowusermedia"; I would expect that to be the most important thing to keep consistent.

**Comment by domenic** [comment]
There's no observable difference in what the name/ID is; as I said that's up to you. I think consistency with fullscreen makes sense given how similar the features are, but we could name it the "allowusermedia flag" if you want; no big deal.

As for browsing context vs. document, I believe in this case there is probably no difference. For fullscreen it has to be per-document, because you can do things like

```js
var doc = document.implementation.createHTMLDocument();
doc.body.requestFullscreen();
```

and here `doc` does not have a browsing context. But for getUserMedia this does not apply.

I can restructure the HTML patch to be per-browsing context if that is preferred, but I thought staying consistent with fullscreen's structure (of making it per document and propagating it upon document creation) would be easier for implementers to reason about. Let me know what you think.

/cc @annevk for discussion of fullscreen's fullscreen enabled flag.

**Comment by alvestrand** [comment]
I'm happy with the proposal. I am mainly asking in order to make sure I understand it.

**Comment by domenic** [comment]
Just curious, is there a timeline on when @adam-be will be able to review? Is there perhaps a regularly scheduled call?

**Comment by adam-be** [comment]
Sorry for taking so long to review this. https://github.com/whatwg/html/pull/1211 LGTM, so please go ahead with the process of moving the spec text.

**Comment by adam-be** [comment]
Proposed fix for this document PR #362

**Comment by alvestrand** [comment]
Solved by #362

**Comment by foolip** [comment]
This came up in https://github.com/whatwg/html/pull/1492.

I don't think this is where the `allowusermedia` attribute was first conceived, but was there any discussion about the compat contraints in actually shipping that model? Per some ad-hoc testing in https://github.com/whatwg/html/pull/1492#issuecomment-230443018 it looks like `getUserMedia()` is currently allowed in iframes, so is any implementer really planning to change this?

**Comment by foolip** [comment]
Sorry, please see https://github.com/w3c/mediacapture-main/issues/268 instead, that's where the attribute was added.
