### ISSUE TITLE
Browser's ability to dynamically change settings mistakenly removed

### ISSUE THREAD

**Issue by burnburn** [w3c/mediacapture-main#394]
In trying to write the PR for issue #360, I (re-) discovered that our long-ago change to use Select Settings only when applyConstraints() is called has effectively eliminated the possibility for the platform to change the settings on its own as long as the constraints continue to be satisfied, which does not match the original intent of constraints.  This needs to be fixed.

**Comment by jan-ivar** [comment]
FWIW, when I implemented `getSettings()` in Firefox 50, I found the biggest omission in the spec in this area to be tabs competing for the camera/microphone (most browsers allow this).

In considering the settings of a singular hardware device, an implementation has to consider constraints from *all* active-gUM tabs, not just one (note there's no per-track downscaling in FF [yet](https://bugzil.la/1286945)).

I don't think the spec needs to lay this out in detail, but probably worth a mention (I devised a way to produce a set of net constraints (or `OverconstrainedError`), given a series of competing constraints).

**Comment by alvestrand** [comment]
I think this belongs in the "life-cycle" section (presently in 4.3.1) - something like "During the lifetime of the track, events such as other requests or external envrionment changes may cause the device's operational mode to change. In such a case, the UA is free to run the "select settings" algorithm again; if the new conditions mean that the present constraints cannot be satisified, it MUST queue a task to fire an "overconstrained" event at the track."

**Comment by jan-ivar** [comment]
@burnburn said "change the settings on its own as long as the constraints continue to be satisfied".

@alvestrand said "if the new conditions mean that the present constraints cannot be satisified, it MUST queue a task to fire an "overconstrained" event"

Which is it?

FWIW Firefox implements the first for competing tabs at least. That is, once you've managed to apply `{exact}` to a capability successfully, another tab can't change it on you, or cause `OverConstrainedError` on you, rather the other tab will fail to apply its competing constraints.

We don't (currently) detect drops in `frameRate` due to lighting or anything like that.

**Comment by alvestrand** [comment]
These two statements are consistent.

**Comment by jan-ivar** [comment]
Perhaps I misunderstood. I interpreted @burnburn's request as wanting to restore the UAs ability to change a source within the envelope of existing constraints on it. If so, this would never throw `OverconstrainedError`. @burnburn is that what you meant?

@alvestrand With "external environment changes" you mean e.g. lighting effects on `frameRate`?

If so, then yes, fire `OverconstrainedEvent` in that case, but I don't think we should lump that together with "other requests". I'd expect new requests to fail rather than succeed and fire `OverconstrainedEvent` on other tracks of the same source, as that seems consistent with *SelectSettings* dictating that `applyConstraints` must leave things alone when it fails. E.g.:

```js
let clone = track.clone();
track.applyConstraints(tougherConstraints); // can fail, but can't overconstrain clone
```

(Conflicts are easier to imagine in browsers that don't add "virtual" settings through rescaling.)

Unfortunately, *SelectSettings* does not address existing constraints from other requests, though I saw just two ways to extrapolate how it should work, and having new concurrent requests fail rather than having them impact existing requests, seemed most consistent with `applyConstraints` leaving existing settings alone.

I basically interpret settings dictionaries that conflict with existing constraints from other requests to be impossible in the sentence "every possible settings dictionary".

Does that match everyone's expectation?

**Comment by jan-ivar** [comment]
https://w3c.github.io/mediacapture-main/getusermedia.html#the-model-sources-sinks-constraints-and-settings supports this:

*"It is possible that constraints can be applied to a track which a source is unable to satisfy, either because the source itself cannot satisfy the constraint or because the source is already satisfying a conflicting constraint. When this happens, the promise returned from applyConstraints() will be rejected, without applying any of the new constraints."*

**Comment by burnburn** [comment]
I can see your concern with "other requests" in Harald's statement.  It is definitely the case that applyConstraints should never itself be able to cause OverconstrainedEvent on any track.  However, SelectSettings should take into account other active constraints for the source.  Say that in a world with only one constrainable property we have track A with constraints that allow for a setting of either 1 or 2 to satisfy the constraints and the UA chooses a setting of 1.  Now we add track B with constraints that allow only for a setting of 2.  In this case the UA should change the source to setting 2, affecting both track A and track B.  If we then add track C with constraints that allow only for a setting of 1 or 3, it should be rejected (even though track A could have accepted this).  Then let's say setting 2 becomes impossible due to environmental changes or other changes to the source availability or configurability due to changes outside the control of the UA.  At that point track B should receive an OverconstrainedEvent and the source should be changed to setting 1, affecting track A.

I believe that this sequence works equivalently when multiple constrainable properties are involved.

If we are agreed on this behavior, then we just need to figure out how to adjust the spec wording to match.

**Comment by jan-ivar** [comment]
@burnburn In that example you still don't have requests triggering OverconstrainedEvent on other requests, unless I missed something. So I agree.

**Comment by jan-ivar** [comment]
> If we then add track C with constraints that allow only for a setting of 1 or 3, it should be rejected

To be specific, here you picked the same outcome I would. The alternative would be to allow track C and fire OverconstrainedError on track B instead, which also produces two working tracks, but I don't like it, because it seems less predictable, and undesirable for tabs to affect others in this way. That's why I prefer first-come-first-serve here.

**Comment by jan-ivar** [comment]
Though first-come-first-serve would prevent a UA from picking favorites, like giving priority to the current tab...

**Comment by alvestrand** [comment]
@jan-ivar I see where the text I proposed looks like "you can fire overconstrained based on someone else's request" now. That's bad drafting on my part; I did not intend it to say that.

In the case of

A: I want (1, 2) => track with setting 1 selected
B: I want (2, 3)

I want the ability for the UA to switch from setting 1 to setting 2.

In the case of

A: I want (1, 2) => track with setting 1 selected
B: I want (3)

then B's request should fail.
I think that's the same thing we're all trying to express.

**Comment by alvestrand** [comment]
Agreement at TPAC about what we should say (slide 37). Dan will write it up.

**Comment by burnburn** [comment]
Apparently the text I expected to see still exists, just below two Notes!  The text currently in the spec says "The User Agent MAY choose new settings for the constrainable properties of the object at any time. When it does so it MUST attempt to satisfy the current Constraints, in the manner described in the algorithm above."

where 'the algorithm above' refers to applyConstraints.  I am comfortable with this text and am comfortable that its interpretation is indeed the one we have agreed to.  @alvestrand , @jan-ivar do either of you have concerns with the existing text?

**Comment by alvestrand** [comment]
I'm happy with the current text; it says what I thought it did. (I may have written it at one point....)

Not sure how to ensure that we always find it when looking for it :-)

**Comment by jan-ivar** [comment]
@burnburn wfm, except I'd like to see s/the current Constraints/all current Constraints/.

**Comment by burnburn** [comment]
@alvestrand I agree with that.  Maybe I'll just move it right above the two notes.  I'll propose that along with JI's mod.
