### ISSUE TITLE
Explanation of "advanced" constraint sets is confusing

### ISSUE THREAD

**Issue by a2sheppy** [w3c/mediacapture-main#396]
Reading section 11 of the spec, past the second example, you come to the description of `advanced` constraints. This description is very dense, with graphs which don't adequately describe how they work. There's a lot of reliance on examples with text which isn't clear.

For example, the phrase "optional constraints" is used to refer to constraints within the `advanced` property, without ever actually saying that advanced constraints are considered optional. Because of that, I assumed that these "optional" constraints were those not included in the `advanced` list.

And the text then talks about using multiple optional constraint sets to achieve a set of fallbacks, but you can't do that outside advanced constraints, so it all becomes increasingly hard to understand. It sounds like  `advanced` is pretty unnecessary given that `ideal` has gravity and the fitness distance algorithm.

Are there any actual scenarios where `advanced` is useful at this point? If so, it would be good to explain these concepts in better detail and more clearly. I actually documented how this stuff works completely wrong because the wording was so hard to interpret in places.

**Comment by alvestrand** [comment]
The word "optional" was used in a previous version of the specification; the functionality was subsumed into "advanced" constraints + (in some cases) the ability to specify "ideal" constraints rather than exact ones. So this was completely opposite your initial understanding.

There are two occurences of "optional" in section 11 where they should have been "advanced",  one in the description of "getConstraints" in 11.1, and three more in the definition of "advanced" at the end of section 11. (I may have missed some).

For larger surgery to the text, I'm afraid we'll have to depend on contributions.
