### ISSUE TITLE
Clarify behavior of using unrelated constraints

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-main#409]
The following programming error is not a `TypeError` in our spec:

``` js
if (navigator.mediaDevices.getSupportedConstraints().width) {
  let stream = await navigator.mediaDevices.getUserMedia({audio: {width: 640}}); // audio
}
```

My best reading of the current spec is that it should be silently ignored, which seems defensible given how dictionary members tend to work ("ignore unrelated members"), so that's not my question.

My question is, should the following reject with `OverconstrainedError`?

``` js
if (navigator.mediaDevices.getSupportedConstraints().width) {
  let stream = await navigator.mediaDevices.getUserMedia({audio: {width: {exact: 640}}});
}
```

It seems to hinge on reading this language:
- _"If the constraint is required ('min', 'max', or 'exact'), and the [settings dictionary](https://w3c.github.io/mediacapture-main/getusermedia.html#dfn-settings-dictionary)'s value for the constraint does not satisfy the constraint, the fitness distance is positive infinity."_

"Satisfy" does not appear defined anywhere. Specifically, it doesn't say how to handle when a settings-dictionary does not have a value for the constraint, i.e. the constraint is irrelevant.

**Comment by martinthomson** [comment]
I think that the only satisfactory answer here is that - if supported - mandatory constraints that are nonsensical cause the track to become overconstrained (or not selected).  That's consistent with asking for fillMode on a camera that doesn't have it.

Non-mandatory constraints can say anything they like.  

Side question: are implementations required to count infinities when determining fitness distance?  For example, if there are two sources and source 1 doesn't support constraint 1 and source 2 doesn't support constraint 2, then you have to fall back to counting fitness distance on both of them based on the constraints they do support.  If you just count to infinity, you lose that ability.

That said, you might not always need to count infinities, just remember that there is one.  If source 1 doesn't support two constraints and source 2 doesn't support one constraint, then falling back on the constraints that each supports is better than saying that source 2 is better because 1∞+n fitness distance is always better than 2∞+m.  Of course, if n or m is unset, then maybe you do need to fall back to counting infinities...

Did I mention that I think constraints are the best thing ever?

**Comment by alvestrand** [comment]
In your example, are you thinking of "ideal" constraints that the various devices don't support?

such as {video: {volume: 50}} or {audio: {width: 640}}?

**Comment by jan-ivar** [comment]
@martinthomson That can't happen, because wrong-domain constraints are equally wrong for all sources in a domain.

The fitness distance algorithm only makes sense for constraints in the valid domain, and infinity should clearly never enter into a distance calculation the way it is written.

I think it's wrong to lump in "future constraints" (for which we have getSupportedConstraints() to detect) with wrong-domain constraints which really should be TypeError or completely ignored IMHO, because *video* will never support *volume*, and thus is always a pilot error.

I think cross-domain constraints are a bad idea for the same reason.

**Comment by martinthomson** [comment]
The infinity thing seems to be an error then.

Is this your conclusion, in order:
 - unknown - ignore
 - wrong-domain - error
 - exact constraints - disregard source if it can't meet them
 - ideal constraints - calculate fitness distance

**Comment by jan-ivar** [comment]
@martinthomson That or: wrong-domain - ignore.

The only thing that holds me back from `TypeError` is that in combination with `getSupportedConstraints` I could see it causing future breakage, like:

```js
let constraints;
if (navigator.mediaDevices.getSupportedConstraints().volume) {
  constraints.volume = { exact: 1};
}
let stream = await
    navigator.mediaDevices.getUserMedia({video: constraints, audio: constraints]);
```

**Comment by jan-ivar** [comment]
Or immediate breakage for that matter once we change it, if they do this today out of convenience:
```js
let constraints = {width: 1280, echoCancellation: false };
let stream = await
    navigator.mediaDevices.getUserMedia({video: constraints, audio: constraints]);
```

**Comment by alvestrand** [comment]
Today a mandatory wrong-domain constraint returns ConstraintError with the constraint name in it. I think that's a more useful response than TypeError.

**Comment by jan-ivar** [comment]
@alvestrand We can put a message in `TypeError`, e.g.:

    TypeError: The 'volume' constraint is not valid on video tracks.

we're always speaking to the script author for such pilot (script) error here. In other words, this isn't an error that scripts would be expected to handle automatically, so I see no advantage in using `OverconstrainedError` for this.

Also, FYI, today only Chrome does this, and only for mandatory constraints.

**Comment by jan-ivar** [comment]
> Also, FYI, today only Chrome does this, and only for mandatory constraints.

Turns out Edge does it as well for mandatory constraints. Firefox does not.

**Comment by jan-ivar** [comment]
`deviceId` is a cross-domain constraint. `TypeError` would still work, unless we were to introduce a new constraint in one domain first, and later change our minds and add it to another domain. In that case `TypeError` would bite us on backwards compatibility.

Given how Chrome and Edge already work, I could live with:

-     unknown - ignore
-     wrong-domain exact constraints - disregard all sources (OverconstrainedError)
-     wrong-domain ideal constraints - ignore (i.e. skip when calculating fitness distance)

**Comment by alvestrand** [comment]
(Chair hat on)
@jan-ivar - wrt behavior for "unknown" and "wrong-domain exact" - since you're reopening a previously discussed topic, and suggesting changes in behavior that is implemented in 2 browsers, I think the onus is on you to explain why any suggested change in behavior is valuable enough to justify reopening this issue.

I'd also suggest contributing tests to the web-platform-tests for this behavior, so that we can see what browsers do in code. That would reduce the chance of misunderstanding.

I'm not so unhappy about suggesting changes in behavior for "ideal", since I know that the current behavior in Chrome for "ideal" is not according to the distance calculation algorithm.

**Comment by alvestrand** [comment]
I think the issue we seem to agree on is that wrong-domain ideal values should not influence the distance metric calculation - they should be ignored.

Perhaps a PR making only that change is in order?

**Comment by alvestrand** [comment]
@jan-ivar do you want to make a PR, or should I?
