### ISSUE TITLE
What does it mean to 'combine' origins?

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-main#532]
This is meaningless to me.  I honestly don't know what it means.  It needs a citation for the combination algorithm, or some more words.

> If the <a>current settings object</a>'s origin is different from <var>originIdentifier</var>, set <var>originIdentifier</var> to the result of combining <var>originIdentifier</var> and the <a>current settings object</a>'s origin.

**Comment by stefhak** [comment]
I _think_ the intention with "combining" was, for the case when an iFrame uses gUM, to be able to both the origin of the Iframe and the page that included the iFrame to the user.
I suspect much of this may be outdated (and may change due to the Permission WS in September).

**Comment by jan-ivar** [comment]
Yes, I recall the intent being to "double-key" origins so a user who grants persistent permission to

 - bar.com in iframe of foo.com website

does not implicitly granted permission to either

 - bar.com website
 - foo.com website

...because it wouldn't be POLA, since most users don't understand iframes or read URLs in prompts.

Feature Policy should simplify, making foo.com responsible for bar.com, which means users grant to:

 - bar.com in iframe of foo.com website
 - foo.com website

but not

 - bar.com website

Do I have that right, @martinthomson ? 

Someone should probably write succinctly what the plan is in https://github.com/w3c/permissions/issues/176.

**Comment by martinthomson** [comment]
The delegation aspect of feature policy (the good half), has the grant given to foo.com always.  foo.com can delegate that capability/permission to frames as it chooses.  bar.com (in the frame) doesn't gain any permissions that it can use.

**Comment by jan-ivar** [comment]
That's a clearer way of explaining it.

**Comment by alvestrand** [comment]
Seems like we should stop combining origins.

**Comment by alvestrand** [comment]
TPAC 2018 decided that combined origins are to be removed from the spec. #548 seems to implement that, so issue can be closed.
