### ISSUE TITLE
What happens to constraints that are not applicable? Ignored or OverconstrainedError?

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-main#533]
WebIDL automatically "filters out" any constraints (members in a dictionary) passed in to getUserMedia() that are not defined in the WebIDL, which means that typos or unrecognized constraints by an implementation would silently be ignored.

However, any constraints that are defined are passed in, regardless if they are applicable or not. I don't know if it's clear what to do in this case, for example if passing in audio-only constraints to a video-only GUM-request. Would the fitness distance for the audio constraint be infinity making getUserMedia() throw an OverconstrainedError, or should it be ignored?

If fitness distance is infinity, does that mean that the following will throw an exception...
```
getUserMedia({video:{volume:{exact:0.5}}})
```
... but the following would pass?
```
getUserMedia({video:{volume:{ideal:0.5}}})
```
Also since this would cause the same "damage" to the fitness distance to ALL sources, are the sources prioritized correctly despite of this or are all of them "infinity" and handled as if they all have the same fitness distance (meaning other constraints would in practice be ignored?)

@guidou Does the GUM algorithm need to be clarified?

**Comment by guidou** [comment]
I think the spec would benefit from clarification in this area.
It is clear that properties that are not supported at all are ignored by WebIDL.
The spec does not explicitly mention what should happen with properties that are intended to be used by only one track type (e.g., echoCancellation).

The practical interpretation seems to be that properties not intended for a track type are ignored.
I tried getUserMedia({video: {echoCancellation: {exact: false}}}) in Chrome, Firefox and Edge, and all of them returned a stream with video track, with no echoCancellation setting.

From an implementation perspective, I think this is the right thing to do. Otherwise, for every new property defined for only one track type, the code for all track types would need to be updated instead of only the code for the intended type.

**Comment by guidou** [comment]
A possible interpretation would be that getUserMedia({video: {echoCancellation: {exact: false}}}) should reject because no video candidate can provide an echoCancellation of false, though fitness distance is positive infinity.

However, it can be argued that a video track definitely has no echoCancellation, so maybe echoCancellation exact false should be accepted.

I think we should update the spec to explicitly say that properties not intended for the track type can be ignored, which would be in line with what browsers currently do.

**Comment by alvestrand** [comment]
that's what is said for &lt;ideal> (ignored). For exact/max/min (mandatory specs), it says explicitly that you should reject with overconstrained.
I think it's wrong to ignore mandatory constraints, so I don't see what we can do but reject.

**Comment by henbos** [comment]
@alvestrand, rejecting for constraints that aren't applicable makes sense, but remember that IDL already forces us to ignore dictionary members that are not known (misspelled constraints or ones not implemented by the browser). Rejecting one invalid parameter (because it is known by the browser), but not rejecting another invalid parameter (because it's not in the IDL), may be perceived as an inconsistency.

**Comment by henbos** [comment]
I created a PR based on @guidou's suggestion (ignore constraints) which does not require existing implementations to be updated and is consistent with how "constraint not implemented" is handled by WebIDL.
