### ISSUE TITLE
Should we allow empty string device IDs?

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#551]
In WebKit, we do want to filter out device IDs provided through enumerateDevices.
This will allow us to give that information to web page:
- after the user grants permission to camera or microphone
- if user granted persistent access to camera or microphone.

This does not seem to be feasible with the current spec except by generating some random IDs if enumerateDevice is called before user grants permission.

A first option would be to make the deviceId attribute nullable.

A second option is for the deviceId value to be the empty string, as a way to limit the potential breakage made to web applications. This seems forbidden as per spec:
"All enumerable devices have an identifier that MUST be unique to the page's origin"

A third option would be to make MediaDeviceInfo a dictionary and only kind would be required.

Any thoughts?

**Comment by alvestrand** [comment]
The previous thinking was that the device ID, being per-origin and opaque, was not worth hiding.

**Comment by jan-ivar** [comment]
My concern would be JavaScript would need to start testing these ids against `""`, which seems like unnecessary breakage.

What Firefox does is return temporal device ids if camera or mic permission has not (yet) been granted, but then reclassifies them as persisted ***if*** the user grants later in the same session, otherwise they are forgotten. That way they remain good for the session.

Additionally, in about:config we have a `privacy.resistFingerprinting` mode where we hide the real devices behind a single `"Default Video Device"` and a single `"Default Audio Device"` (their labels hidden before grant), with their own device ids that work similarly.

Could you do something similar? AFAIK there's no requirement that [label](https://w3c.github.io/mediacapture-main/getusermedia.html#dom-mediastreamtrack-label) remain stable.

**Comment by jan-ivar** [comment]
Another, perhaps hacky, option might be to do [what Chrome does for their redundant "default mic" entry](https://stackoverflow.com/a/53308831/918910) which is to give it a deviceId of the special value `"default"` or similar.

**Comment by youennf** [comment]
> What Firefox does is return temporal device ids if camera or mic permission has not (yet) been granted, but then reclassifies them as persisted _**if**_ the user grants later in the same session, otherwise they are forgotten. That way they remain good for the session.

It then means that the device IDs persist after the user granted permission once.
I do not think WebKit would implement this behavior.

> Another, perhaps hacky, option might be to do [what Chrome does for their redundant "default mic" entry](https://stackoverflow.com/a/53308831/918910) which is to give it a deviceId of the special value `"default"` or similar.

What is the difference between "default" and "" in that case?
In both cases, the device IDs might not be unique per-origin.

**Comment by jan-ivar** [comment]
> It then means that the device IDs persist after the user granted permission once.
> I do not think WebKit would implement this behavior.

The spec [says](https://w3c.github.io/mediacapture-main/getusermedia.html#def-constraint-deviceId): *"The same identifier MUST be valid between browsing sessions of this origin, but MUST also be different for other origins."*

[and](https://w3c.github.io/mediacapture-main/getusermedia.html#constrainable-interface): *"If any local devices have been attached to a live MediaStreamTrack in a page from this origin, or stored permission to access local devices has been granted to this origin, then this identifier MUST be persisted, except as detailed below."*

We decided sites are responsible for managing devices for users. How is a site to remember a user's choice without this?

But that's irrelevant to my point here: In Firefox, `deviceId` is invariant; it's always honored, and never changes from `""` to something else during the session, which is the part I object to.

> What is the difference between "default" and "" in that case?
In both cases, the device IDs might not be unique per-origin.

`"default"` is invariant. You're right it's not origin-unique, so it technically violates the spec. However, because of how it's is implemented—always giving you the system default—it reveals no information about the user's system, so I'd say it's following the spirit if not the letter of the spec.

**Comment by youennf** [comment]
> We decided sites are responsible for managing devices for users. How is a site to remember a user's choice without this?

I was thinking of the following workflow:

On first time user visit, the web site will do:
1. Call enumerateDevices to check for camera/microphone
2. Call getUserMedia and receive audio/video MediaStreamTracks
3. Store the mic/camera deviceIds attached to the MediaStreamTracks, say in IDB

On the user second visit, the website will do:
1. Retrieve the deviceIds audioDevice1 and videoDevice1 from IDB
2. Call getUserMedia({audio: {deviceId: audioDevice1}, video : {deviceId: videoDevice1})
    Browser will provide the content of the expected devices if they still do exist and if user did not remove cookies. Otherwise, default devices will be used.
3. Update IDB stored deviceIds if needed

AIUIC, during the second visit, device labels would be initially filtered out.
But, since device IDs would be persistent and exposed, the web page could easily retrieve device labels by storing them during the first visit and pairing them with device IDs on second visit.
This seems to somehow contradict label filtering.
It is true though that this would enable the possibility for a device picker early on in the web page flow, should the browser to provide a full list of devices. Safari does not plan to provide this full list though.
And I haven't seen web sites with that flow either.

What functionality would Safari proposed behavior prevent?

**Comment by youennf** [comment]
> > What is the difference between "default" and "" in that case?
> > In both cases, the device IDs might not be unique per-origin.
> 
> `"default"` is invariant

I see, so 'default' is supposed to stay like this for the lifetime of the page.
And your issue is really that we would change deviceIds from default or "" to actual values during the lifetime of the page.

**Comment by youennf** [comment]
An edge case where, in Safari, device IDs values are already changing:
1 A web page is granted getUserMedia permission
2 The web page does enumerate devices
3 The user flushes cookies for this origin
4 The web page does enumerate devices again
Device IDs will be different in steps 2 and 4.

**Comment by youennf** [comment]
Wrote a simple test as per the current behavior
https://github.com/youennf/web-platform-tests/commit/0ec50cba19569aa5018d8b722f0e9fb8428fc7d7
Safari and Chrome fails, Mozilla succeeds.

**Comment by jan-ivar** [comment]
> the default devices are removed and the real devices appear as new devices.

That might work, but in that case I would expect a `devicechange` event to fire. I'd also expect the *deviceId* to be usable in *getUserMedia* before the event but not after, or perhaps during.

> allow some values (empty string, 'default') to be the same cross-origin.

What does this accomplish that a random id doesn't?

**Comment by youennf** [comment]
> That might work, but in that case I would expect a `devicechange` event to fire. I'd also expect the _deviceId_ to be usable in _getUserMedia_ before the event but not after, or perhaps during.

I am fine allowing this value in getUserMedia anytime (before and after).
As long as a MediaStreamTrack is live, you would expect that calling the same getUserMedia call should succeed.

> > allow some values (empty string, 'default') to be the same cross-origin.
> 
> What does this accomplish that a random id doesn't?

Implementation-wise, this is more difficult to implement since you need to recall that this random value is actually equivalent to a default deviceId.
And it does not bring any value since it is not hiding anything.

'default'/empty string also convey in a better way the intent, which is to tell to the web page whether there is any available camera/microphone device, not whether there is a particular specific device that can be targeted.

That said, enumerateDevices should not even be used to check for camera/microphone existence in Safari since non default devices are not exposed. Maybe the solution is to just not return any device until it is proven that users have some confidence in the web site.

**Comment by jan-ivar** [comment]
> it does not bring any value since it is not hiding anything.

The value added is it fits within the existing spec; we've not added to the cognitive load of the model exposed to users, which trumps implementation difficulties in the [priority of constintuencies](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies).

> 'default'/empty string also convey in a better way the intent, 

FWIW Chrome only supports this special "default" deviceId for microphones, not cameras, and Firefox recently removed this feature altogether, so I don't think we're keen on adding it back.

Currently in the spec, there's no expectation that users look at deviceIds to infer any special meaning. If they do then it's not web compatible.

> That said, enumerateDevices should not even be used to check for camera/microphone existence in Safari since non default devices are not exposed.

If users have to check they're on Safari, then we've failed. Presumably sites are already using this API to check for existence, as that works on most browsers today, and is an implicit guarantee in the model exposed in this spec. It seems late to change this.

**Comment by jan-ivar** [comment]
Another way to look at a random id approach:
1. All ids are fresh ones when not persisted from a previous session.
1. Before gUM is granted, expose the id of the camera and mic that is the default at that time.
2. After gUM is granted, expose any additional ids, if the user has several devices.

Where's the extra work?

**Comment by jan-ivar** [comment]
> But, since device IDs would be persistent and exposed, the web page could easily retrieve device labels by storing them during the first visit and pairing them with device IDs on second visit.

The web page could likewise store the entire list of deviceIds and labels from the first visit for use on subsequent visits—Most users don't change their device setup too often.

We can compare exposure to what is already possible with IDB (cookies/localStorage/IDB):
 1.  nothing from enumerateDevices(), relying solely on IDB: all devices and labels from last time.
 2. deviceIds from enumerateDevices() vs from IDB: + number of a/v devices added/removed since.
 3. labels from enumerateDevices() vs from IDB: + names of new devices previously unknown.

(3) exposes actual new information.
(2) is the net privacy trade-off the spec has made, in the interest of aiding repeat visitors.

**Comment by youennf** [comment]
> (2) is the net privacy trade-off the spec has made, in the interest of aiding repeat visitors.

Can you describe how enumerateDevices helps repeating visitors?
getUserMedia({audio: deviceId: {ideal: previouslyUsedAudioDeviceId}}) should do the trick for them, previouslyUsedAudioDeviceId being grabbed from MediaStreamTrack.getSettings().
No need for enumerateDevices or am I missing something?

enumerateDevices seems mostly useful for building a device picker, which tends to happen after getUserMedia prompt so that nice previews can be displayed.

> The web page could likewise store the entire list of deviceIds and labels from the first visit for use on subsequent visits—Most users don't change their device setup too often.

This would indicate to me that there is no need for providing detailed enumerateDevices on the second visit ;)

That said, I can see some cases that might make a setup change happen repeatedly:
1. BT headsets on mobile devices might be problematic if they can be enumerated as well when paired.
2. Laptop connected to/disconnected from secondary screens with camera/microphone might be another case. Let's say this is the configuration I have both at home and at my office.
Any web site that I granted permission to access my camera once, could then, based on deviceIds, know whether I am at home, at my office or somewhere else.

If we look at the specific issue of picking the right device when getUserMedia is called for the first time on a page, isn't it the browser that could do the best job, and without the privacy concerns.

**Comment by youennf** [comment]
Fixed by #587
