### ISSUE TITLE
should enumerateDevices list infrared cameras by default?

### ISSUE THREAD

**Issue by fippo** [w3c/mediacapture-main#553]
I just noticed that my Surface Book (windows insider build Version 1809 OS Build 17763.1) exposed the  "Microsoft IR camera front" on https://webrtc.github.io/samples/src/content/devices/input-output/
Only in Chrome, Edge and Firefox seem to filter that device.

Exposing that device doesn't make much sense for normal videochat applications.
It does have some potentially cool applications though.

@aboba @guidou thoughts?

**Comment by alvestrand** [comment]
This is a good case of "we need to know more" - I don't see a good case for hiding the camera, since that will make it impossible to write applications that use it.
We discussed some time ago the idea of making the capabilities of a device available in enumerateDevices ; "frequencyRange" seems like one of the capabilities that could be exposed.
This is fingerprinting surface, of course, so would probably be only available to "authorized" apps (by whatever mechanism).

**Comment by jan-ivar** [comment]
`enumerateDevices` should list all `deviceIds` that will work with `getUserMedia`.

**Comment by alvestrand** [comment]
Closing as "no change needed".

**Comment by KaKi87** [comment]
Hello, so what is the actual solution to remove those cameras ? Thanks

**Comment by jan-ivar** [comment]
Most likely https://github.com/w3c/mediacapture-extensions/issues/14.

**Comment by jan-ivar** [comment]
If you're looking for a workaround, look for " IR " in the label.
