### ISSUE TITLE
Echo Cancellation

### ISSUE THREAD

**Issue by jgupta** [w3c/mediacapture-main#597]
On #577 echo cancellation definition was changed to make the scope more explicit. However, I am confused by [several comments](https://bugs.chromium.org/p/chromium/issues/detail?id=687574#c38) made [by the Chrome team](https://bugs.chromium.org/p/chromium/issues/detail?id=687574#c40).

What is the use of echoCancellation property in spec if it does not make it clear that echo cancellation must attempt to remove all sounds from the input. Does [echo cancellation definition](https://w3c.github.io/mediacapture-main/#def-constraint-echoCancellation) not considered part of spec or is it that definition itself is not clear?

**Comment by henbos** [comment]
I believe the intention is to allow browsers to perform echo cancellation to the best of its abilities, but to give applications control of turning it off if it has undesired consequences. It's hard to write hard requirements of what an echo canceller "MUST" be able to achieve because a browser's echo cancellation mechanisms are very much an implementation detail of the browser. There is no standardized ehco cancellation algorithm.

**Comment by jgupta** [comment]
It is not about what it must be able to achieve (performance) or about the algorithm or implementation detail but what it should attempt to be doing.

1. Echo Cancellation should be turned off or on depending on echoCancellation property.
2. When echoCancellation is turned on, then as per [definition](https://w3c.github.io/mediacapture-main/#def-constraint-echoCancellation) browser should attempt to remove all the sound being played from the input signals recorded by the microphones.

All browsers seem to following point (1).
Edge, Firefox, Safari seems to be the following point (2).

Chrome, however, seems to be moving away from specs as it only attempts to remove sound from **only remote peer** and not **all** sounds as mentioned in sepc definition.

**Comment by henbos** [comment]
It's debatable if it should be a "recommends", a "SHOULD" or a "MUST" to have echo cancellation apply to everything. But even if it's a "MUST" to _attempt to remove all the sound_, you can easily imagine a browser that _attempts_ to remove echo from WebAudio but it just isn't very good at doing so, and you end up with echo anyway. This relates to the problem that _how to do echo cancellation_ is outside the scope of the spec, and without any objective, testable requirements about what is or is not "good enough", it would be hard to tell a bad implementation from a spec-non-compliant implementation. The spec is vague here on purpose. We _could_ upgrade the language to a hard SHOULD, but SHOULDs are optional to implement.

Without major revisions to the spec, what this really boils down to is if the **Type** field on the chromium bug should say "Bug" or "Feature". Which does not necessarily dictate the **Pri** field.

I would focus my efforts on why it's a good idea to improve Chrome's implementation or how many would benefit from it rather than revisiting the spec's definition. In any case, it's up to the Chromium team how the Chromium team prioritizes bugs and features.

I'm suggesting to close this spec issue.

**Comment by jgupta** [comment]
I don't understand why are you talking about performance or guarantees or how to do echo cancellation? It is totally ok if browsers attempt to remove echo but fail to do so due to limitations.

I also understand that Chrome may choose to remain non-compliant to specs until they wish to.

All I am saying is that different browsers are interpreting specs differently. Chrome, in this case, insists that by not attempting to remove all sounds (only working on sound from remote peer) they are not in violation with specs. So, do we need to make specs more explicit or are specs clear enough?

**Comment by henbos** [comment]
We could make it a "MUST attempt" to further guide implementations but Chrome's current implementation (no attempt), while it would then be a "bug" rather than a "feature", it would not be _observably different_ than a terrible attempt (which would be spec-compliant). As such, the difference between a should and a must in these under-specified areas are mostly philosophical.

**Comment by guidou** [comment]
"MUST attempt"  sounds like a bad idea for a spec because a failed attempt (spec compliant) is indistinguishable from no attempt (not spec compliant). Thus, it is impossible to test conformance.

**Comment by alvestrand** [comment]
If there is no difference, it's hard to claim conformance.

However, I'd like to see a test setup that demonstrates the difference between version 1) and 2) in comment #3 - if we can make that a test that (old) Edge, Firefox and Safari pass and Chrome fails, then we have something that can be the basis of a testable definition.

**Comment by jgupta** [comment]
Basic Test Code: https://jsfiddle.net/mdzcpaqo/1/

Testing it in Chrome is most simple, we just need to chrome://webrtc-internals/ and enable diagnostic audio. If echo cancellation kicks in, we should see a reverse file having some size (we can open it in an audio editor).

Testing it with other browsers is a bit complex due to lack of tools, we had to record microphone input and analyse it ourselves. We also tested it practically by transmitting audio between two people via WebSockets.

We have tested it, some people have also commented the same in chromium bug [#687574](https://bugs.chromium.org/p/chromium/issues/detail?id=687574). People here might want to test some independently.

**Comment by jan-ivar** [comment]
This API allows user agents to do echo cancellation. How well an implementation does that is generally an issue that should be raised with that implementation, as it is not a spec of web compat issue or issue with the API. That is, unless a separate control surface is needed for different kinds of echo cancellations.
