### ISSUE TITLE
Handling of rotation for camera capture streams

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#660]
Both Safari and Chrome (not sure about Firefox) do change width and height when capturing device (mobile device typically) is rotating.
Basically, width and height are swapped.

This isn't specified anywhere and I am wondering whether this should be something we should take some time to describe.
I am also wondering how things are exposed in terms of settings/constraints getters so that web pages can notice this.
Is it also a behavior that web pages always want? Should we provide an opt-out?

**Comment by jan-ivar** [comment]
Example:
```
a=extmap:13 urn:3gpp:video-orientation
```

**Comment by jan-ivar** [comment]
> Both Safari and Chrome (not sure about Firefox) do change width and height when capturing device (mobile device typically) is rotating.
Basically, width and height are swapped.

Firefox does as well. Tested with https://jsfiddle.net/jib1/6a0shctq/

Interestingly, `getCapabilities()` values are NOT swapped. Tested in all browsers except Safari (I don't have an iphone) and Firefox (doesn't implement it yet).

> More queries: What if width, height and/or aspect ratio are constrained to a specific value?

Looks like all browsers apply constraints to landscape. Tested with `{width: {min: 641}}` https://jsfiddle.net/jib1/e5dkao41/ which on my Samsung s8 produces:
```js
{
  "width": 480,
  "height": 720
}
```
Since we don't have the `overconstrained` event anymore, this is probably just as well.

Is this what we want to specify?
