### ISSUE TITLE
What happens when a machine suspends?

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-main#668]
As part of discussion on https://github.com/w3c/webrtc-pc/issues/2489, it's become clear that we don't know what a track is supposed to do when a machine suspends.

It seems logical to mute cameras and microphones, and not unmute them before machine is unlocked. It might also be logical to end the tracks (permanently).

**Comment by dontcallmedom** [comment]
Does the [WICG Lifecyle API](https://wicg.github.io/page-lifecycle/) help modeling what we need to do here? Can it be made to help if not?

**Comment by henbos** [comment]
That looks very relevant!

**Comment by alvestrand** [comment]
To me it seems that:
1) the event we're looking for seems to be the "change the frozenness" event, triggered at https://wicg.github.io/page-lifecycle/#frozenness-state
2) when frozenness changes to frozen, it makes sense to mute all tracks with device sources (mediacapture-main); when frozenness changes to unfrozen, it makes sense to require some specific action (page in front? user interaction?) before unmuting.
3) there is no chance for JS to gain control between frozen and discarded state.
4) when returning to a discarded context, there will be a "discarded" boolean - but I don't think anything else from the previous context survives? We shouldn't specify anything here, I think.

What else?

**Comment by youennf** [comment]
> 2\. when frozenness changes to frozen, it makes sense to mute all tracks with device sources

From the page perspective, this is irrelevant since this will not be observable to the page.
User agents could try to update the capture indicator, but I am not sure the spec should mandate anything here.

> 2\. when frozenness changes to unfrozen, it makes sense to require some specific action (page in front? user interaction?) before unmuting.

I would love to be able to converge there, but this is a difficult area.
Also, I am not sure frozen is the right concept since this is mostly irrelevant/invisible to the user.
Frozen is something that might be highly time/memory/cpu/battery dependent and only time seems somehow meaningful to the user.

For instance on iOS, a page only capturing video will get video-capture-muted as soon as it goes in the background. It will probably then quickly become frozen. If the page is generating audio though, it might not become frozen. Should there be two different behaviours? Maybe, maybe bit. In both cases currently, Safari will restart video capture if page goes back to foreground.

> 4\. when returning to a discarded context, there will be a "discarded" boolean - but I don't think anything else from the previous context survives?

Agreed.

**Comment by guest271314** [comment]
There is the case of a user closing the laptop lid, or otherwise the machine "suspends" or is suspended on purpose while the user still expects work to be done by the browser. For example, the machine clock still runs when the machine "suspends", reflected by the accurate time when the machine un-"suspends". `cron` jobs or other native applications and code can still run depending on how "suspend" is configured at the machine and OS. The user can still use the data exchanged during "suspends" after "suspends". That is the purpose of having a machine to do work, it only does what you program it to do. Leave it up to the user to decide what should occur when a machine "suspends" `{options: {suspend: (state) => state === "suspended|hibernate|notFocused|et al" ? this.mediaStreamTrack.enabled : /* do something else unless specification states no computing can occur when machine is "suspended" */}}` instead of trying to define top-down must-occurs with the input of only several authors that cannot possibly conceive of every use case.

**Comment by jan-ivar** [comment]
As I mention in https://github.com/w3c/webrtc-pc/issues/2489#issuecomment-602879082 I don't think we need that new JS API to define what happens when a machine suspends.

We don't even know if that API promises to fire events on all tabs when the whole OS suspends (does it?) Whether it does or not, seems irrelevant to defining our behaviors.

I think it's fair to assume that when an OS temporarily suspends everything, all system state halts, and resumes later. I don't know that we can promise to fire `mute` and `unmute` in these cases, can we?

**Comment by guest271314** [comment]
> I think it's fair to assume that when an OS temporarily suspends everything, all system state halts, and resumes later.

That depends entirely on how the user has configured the machine and OS. 

A user could decide to close the lid on a laptop and expect the running program to continue, because they have set the appropriate values at machine and/or OS level to do just that. `cron` jobs which launch GUI and headless browsers to continue computing; perform tasks when human interaction is not necessary; do not want or need any one else, or self, seeing what data is being processed by the browser, OS, machine on a screen or terminal. 

`mute`, `unmute`, and `ended` events are currently not consistent between implementations. Implementers are, or shouldd be aware of the inconsistency with regard to the above-listed events at browsers, yet have not fixed those issues to at least be consistent, yet nonetheless will now embark on a path to define what to do "when a machine suspends" which is a very broad term. 

There is no possible way to determine precisely how all handhelds, laptops, or desktops are configured re "suspend", "hibernate", etc. other than to test each device individually to determine the means by which "suspends" occurs and un-"suspends".

What is the compelling need for Media Capture and Streams to delve into where a machine - not just the browser where a `MediaStream` and `MediaStreamTrack` are being used - is "suspended"? 

Would not a more concrete project be to at least work to make the `mute`, `unmute`, and `ended` events of the various extensions of `MediaStreamTrack` truly compatible and consistent?

**Comment by jan-ivar** [comment]
> Would not a more concrete project be to at least work to make the mute, unmute, and ended events of the various extensions of MediaStreamTrack truly compatible and consistent?

I opened https://github.com/w3c/mediacapture-main/issues/670 for this.

**Comment by jan-ivar** [comment]
Sorry that was confusing. What I meant to say was I opened https://github.com/w3c/mediacapture-main/issues/670 to make `mute` and `unmute` on _camera_ and _microphone_ tracks work consistently in all browsers, not to make them consistent with other specs (other specs are on their own).

**Comment by guest271314** [comment]
> Sorry that was confusing. What I meant to say was I opened #670 to make `mute` and `unmute` on _camera_ and _microphone_ tracks work consistently in all browsers, not to make them consistent with other specs (other specs are on their own).

They all link back here. This specification is primary source for `MediaStream` and `MediaStreamTrack`. It is not possible to avoid addressing the wild inconsistency between Chromium and Firefox as to `mute`, `unmute`, and `ended` of `MediaStreamTrack` when actually testing the implementation of this specification at modern browsers. Yet, for an unclear reason the momentum is to add more load to `mute`, `unmute` and `ended`, which by result of the reference back to this specification for the extensions will further make the `MediaStream` and `MediaStreamTrack` implementation with a core document where their own is really not their own, their own is using the "branded" `MediaStream` and `MediaStreamTrack`. 

Why is "What happens when a machine suspends?" a compelling concern?  

Do the specification authors intended to actually perform field research, or only speculate from the top-down as to what should occur when "a machine suspends"? 

Is this a directive from you parent corporation or other subsidiary working group to address that issue?

What happens when a user does not want browser source code to be constantly checking some vague notion of what "when a machine suspends" is supposed to mean and wants to opt-out of the concept of `getUserMedia()` is spying on when the laptop lid is closed, or some other arbitrary and intrusive browser code?

**Comment by jan-ivar** [comment]
From [minutes](https://lists.w3.org/Archives/Public/public-webrtc/2020Apr/0074.html):
> We couldn’t find a DOM event for suspend. Editors concluded nothing happens to peer connections on suspend. But what about devices?
> 
> Closing the lid and opening it again: it could still be capturing prior to logging in!
>
> Proposal: Fire muted on suspend, unmute when unlocking - not before! Is it specifiable?
> 
> Jan-Ivar: When you lock the screen the page doesn’t actually suspend. Can we piggyback on whether or not playout should happen?
> 
> Discussion: Maybe this should be up to the user agent but we should definitely not be creepy.
> 
> Next steps: Let’s write guidelines.

"Suspend" may be the wrong word here, but I'll try to write a PR to capture the above.

**Comment by guest271314** [comment]
> Closing the lid and opening it again: it could still be capturing prior to logging in!

"Suspend" is not guranteed to occur when laptop lid closes. What evidence is that theory based on?

There is  no way for the specification to address every  case of user configuration of machine OS power manager, window manager, display manager.

The specification authors should not rely on conjecture, or write the specification with only their individual default machine settings as the basis for attempting to define a "suspend"-like case. 

No guidelines are necessary. No language in any specification can take into account the various ways a user can configure their machine to continue computing or not.

If the authors insist "guidelines" must be specified, leave it up to the user, not the user agent, to configure what should occur when laptop lid closes: only they will know their own configurations, and are best suited to catch the case for the machine they happen to be using. 


Have any tests been performed, with varying power manager, window manager, display manager settings at different OS'es to actually determibe if any prospective "guidelines" on paper can actually be implemented remotely uniformly? 

That would appear to be the practical step to take, intead of writing words on paper first without any evidence that such words can be applied in a compatible and uniform manner using the exact same text, processes and procedures.

**Comment by guest271314** [comment]
@jan-ivar 

> Closing the lid and opening it again: it could still be capturing prior to logging in!

One workaround for the case of a `MediaStream` from `getUserMedia()` where the camera is actually on the screen side of laptop  is to check the pixels for equivalent of a "black" frame. Tested at Nightly 77
```

function checkPixels() {
  /* e.g., stream && stream.active || recorder && recorder.state === 'recording' */
  if (condition) {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
    const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
    for (let r = 0; r < imageData.data.length; r+=4) {
     // does not have to be 0,0,0,255 to be a "black" frame
     // every 4 indexes could be 0,2,0,255 or 0,2,3,255
     // if all 3 indexes (RGB) are less than 10 (test, set lower values here)
     if (imageData.data[r] + imageData.data[r+1] + imageData.data[r+2] < 10) {
       tracks.forEach(track => track.stop());
       return;
     }
   }
    // set time to analyze MediaStreamTrack through <video> here
    setTimeout(() =>  checkPixels(), 1000); 
  }
}
navigator.mediaDevices.getUserMedia({audio:true, video: true})
.then(_ => {
  stream = _;
  tracks  =  stream.getTracks();
  // Firefox does not support ImageCapture, else could capture MediaStreamTrack as ImageBitmap
  // instead of streaming content through HTMLVideoElement
  video.srcObject = stream;
  // recorder = new MediaRecorder(video.srcObject);
  // wait 1 second to avoid first frame being 0,0,0,255
  setTimeout(() =>  checkPixels(), 1000);
  // recorder.start();
})
.catch(console.error);
```
Does not address the case of external and/or camera(s) not on screen side where closing laptop lid will not impact input video stream.

Another option would be to clone the audio input stream, if any,  or create an audio stream if not present in original input or output stream, then use speech recognition (official Web SPeech API implementations or, e.g., pocketsphinx https://github.com/syl22-00/pocketsphinx.js) to execute `stop()` on each track when keywords "end session" or "logout" are included in the transcript result.

**Comment by guest271314** [comment]
The code at https://github.com/w3c/mediacapture-main/issues/668#issuecomment-622997049 achieves the same result at Chromium 81.0.4044.122 (stable).

The tests were performed without adjusting default Power Manager settings at OS (4.15.0-20-lowlatency, i686 GNU/Linux).

The default setting for when laptop lid is closed is "Lock screen". 

When setting the value to "Suspend" and `checkPixels()` is not executed the `MediaStream` is still being rendered at `<video>` element after closing laptop lid for 1 minute.

Have not tried "Hibernate" or "Switch off diplay" options.

![Screenshot_2020-05-02_21-39-21](https://user-images.githubusercontent.com/4174848/80893065-8ddd8000-8cbe-11ea-9321-1db517a77049.png)

**Comment by guest271314** [comment]
> We couldn’t find a DOM event for suspend. Editors concluded nothing happens to peer connections on suspend. But what about devices?

When "Suspend" is set at Power Manager or equivalent OS settings application and `RTCPeerConnection` is used with `addTrack()` to send local tracks to remote peer `iceconnectionstatechange` event _is_ fired and `iceConnectionState` is set to `"disconnected"`, that _does not_ occur when the local setting is "Lock screen" (the default setting at particular OS currently using).

As described above the stream continues without observable interruption when `getUserMedia()` is executed and displayed locally. The API which this appears to impact and is pertinent is remote streams using `RTCPeerConnection`, where the `iceconnectionstatechange` event is observable - when the user expliticly sets "Suspend" option for what to do when laptop lid closes at the OS, not necessarily using the default settings (could be any OS from *indows to Ma* to any *nix distribution).

**Comment by guest271314** [comment]
It follows that when the user _explicitly sets_ "Suspend" at OS Power Manager or equivalent native settings GUI or at command-line for the case of "When laptop lid is closed" if the user really wants to stop the local tracks, or do something else, that can be achieved awaiting `iceconnectionstatechange` event and `iceConnectionState` value `"disconnected"`

```

pc1.oniceconnectionstatechange = () => { 
  if (pc1.iceConnectionState === "disconnected") {
    for (const sender of pc1.getSenders()) {
       sender.track.stop();
    };
  };
};
```
Tested at Nightly 77 and Chromium 81. The only difference in the result is Chromium prints `Uncaught (in promise) TypeError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Candidate missing values for both sdpMid and sdpMLineIndex
    at RTCPeerConnection.pc2.onicecandidate`.
