### ISSUE TITLE
applyConstraints algorithm is imprecise in how to select the actual settings values

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-main#729]
Step 6 of the algorithm is stating "Select one settings dictionary from candidates, and return it as the result of the SelectSettings algorithm. The UA SHOULD use the one with the smallest fitness distance, as calculated in step 3, but MAY prefer ones with resizeMode set to "none" over "crop-and-scale".

It is not clear how to implement consistently the selection since several settings might have the same fitness distance.
Should the specification define how to break potential ties.
Also, is there a way we could try to have MUST instead of SHOULD+MAY.

Experiments should be done to understand how big this is an actual interoperability issue.

**Comment by guest271314** [comment]
Am all for, ready and willing to perform experiments to yield empirical evidence. 

Those "MAY"'s, as you indicate, leave implementations room to do whatever they want, or do nothing. 

Though how do you mandate any specific outcome when there is no singular, consistent device with which the tests are from a baseline? The types and models of devices and the capabilities thereof are vast. 

Even when the language in the specification is clear implementations are not consistent https://github.com/w3c/mediacapture-output/issues/113.

What is the goal to achieve, in code, with regard to `applyConstraints()`? 

What is not occurring now that this issue seeks to solve?

**Comment by guest271314** [comment]
This issue https://github.com/w3c/mediacapture-screen-share/issues/105 was closed by https://github.com/w3c/mediacapture-screen-share/issues/105#issuecomment-521667012

> This seems to be possible to do with current APIs, so no compelling reason seen for more browser surface.

where, if considered applicable at Screen Share, the same appears to be applicable here. That is, get the original captured image, manipulate the image any way you want to, use the manipulated image as source for the video expected to be created.

Otherwise we place a great amount of responsibility on implementations to effectively edit videos in real-time, where, so far the empirical evidence is that Chromium still captures the prompt they have developed which can contain screens, applications, monitors not intended to be captured in the first 7 seconds of the capture. So, no matter if the correct constraints are applied, it is still possible to get user data not intended to be exposed, and capture a prompt that could very well be meaningless to the stream intended to be created, by overlaying the actual screen intended to be captured.

Now, you have already merged the PR to fix that. Yet Chromium evidently ignored the memo. Thus, why would users - and the authors of this specification - trust implementations to precisely apply constraints, consistently?

**Comment by jan-ivar** [comment]
> The UA SHOULD use the one with the smallest fitness distance, as calculated in step 3, but MAY prefer ones with resizeMode set to "none" over "crop-and-scale".

> Also, is there a way we could try to have MUST instead of SHOULD+MAY.

I would support MUST here and removing the MAY.

The MAY was my attempt at preserving Firefox's `advanced` behavior, e.g.:
```js
await getUserMedia({video: {width: 640, height: 480, advanced: [
  {width: 1280, height: 768},
  {width: 1280, height: 768},
  {width: 640, height: 480},
]}});
```
...since I didn't think `advanced` made any sense unless the settings dictionaries being triaged were native modes.

But in hindsight, there's a web compatible fix for that:
```js
await getUserMedia({video: {width: 640, height: 480, advanced: [
  {resizeMode: "none"},
  {width: 1280, height: 768},
  {width: 1280, height: 768},
  {width: 640, height: 480},
]}});
```
...so I think we're willing to break backwards compatibility with anyone relying on the old Firefox behavior of the former.

I _believe_ the SHOULD is only there to support the MAY.

**Comment by jan-ivar** [comment]
@jan-ivar to bring to editor's call
