### ISSUE TITLE
Provide a little more transparency into the inner workings of getUserMedia

### ISSUE THREAD

**Issue by q-alex-zhao** [w3c/mediacapture-main#764]
As an application developer I'd like to give the user a bit more help in guiding them through the video calling experience. Particularly when calling `getUserMedia` and the resulting promise does not resolve immediately:

- Does it mean that the user agent is showing the permissions prompt? In that case the application may want to tell the user to find that prompt and deal with that first, which is not always obvious to the user.
- Does it mean that the device (e.g. camera) is simply slow to open? In that case the application may tell the user be patient.
- Does it mean the system is under too much load or is too slow to respond? The application should probably do nothing here.
- Or it could be a bug where the promise never settles. The application could use a reasonably large timeout to catch this, so this is already covered.

Thanks.

**Comment by youennf** [comment]
> * Does it mean that the user agent is showing the permissions prompt? In that case the application may want to tell the user to find that prompt and deal with that first, which is not always obvious to the user.

I think there is value in exposing whether there will be a prompt or not.
The Permissions API may help since it has Deny/Grant/Prompt values.
For Safari, we are not sure about the 'Deny' case though but Grant/Prompt should be sufficient for you.

> * Does it mean that the device (e.g. camera) is simply slow to open? In that case the application may tell the user be patient.

This is not really covered though opening the device is implementation dependent and can have several meanings.
I am not sure what we could do. I am not sure there is a justification for a new API surfacing getUserMedia decision taken from device opening. In some other issue, we are considering delaying actual opening of the device just before getUserMedia promise resolution callback to limit device recalibration.

There is also the case where getUserMedia processing is delayed until the page has focus.
In general, it seems best for an application to request getUserMedia access based on a user gesture.

**Comment by q-alex-zhao** [comment]
Ah this makes sense. Thanks.

**Comment by q-alex-zhao** [comment]
Except Firefox doesn't seem to support the camera or microphone `PermissionName` enum, yet. And Safari doesn't support the permissions API.
