### ISSUE TITLE
What is the purpose of MediaTrackCapabilities displaySurface?

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-main#915]
Hello folks, the spec currently says `getCapabilities()` should return the current [displaySurface](1) value (either `"monitor"`, `"window"`, or `"browser"`).  Note that it was added in https://github.com/w3c/mediacapture-screen-share/pull/84

I'm now wondering what purpose is served by exposing this capability? Is it for simple parity with `getSettings().displaySurface`? I'd love to understand how web developers could use `if (videoTrack.getCapabilities().displaySurface === "browser") ...` condition for instance?

Thanks for your time!

[1]: https://w3c.github.io/mediacapture-screen-share/#dom-mediatrackcapabilities-displaysurface

**Comment by jan-ivar** [comment]
> If, on the current track the range/set consists of a single value, we run into the question of "value" vs. ["value"]. That's an orthogonal question. If you wish to discuss it, let's do so separately.

I believe that's inaccurate. e.g. [channelCount](https://w3c.github.io/mediacapture-main/#def-constraint-channelCount) is well-defined to take a range. The [editor's mistake](https://github.com/w3c/mediacapture-main/commit/059a9211d1622094dd8857db9beb477976f971dd) seemed limited to "properties that cannot ever be changed", to use your definition (facingMode was later corrected).

I don't think it's orthogonal either, as it hopefully explains part of the OP's _"spec currently says getCapabilities() should return the current [displaySurface](https://github.com/w3c/mediacapture-main/issues/1) value"_ confusion. I.e. it might have been less confusing if it had said to return an array with the current settings value in it (since that's the only value that can be set with applyConstraints).

 I'm still not clear on whether this issue chases utility or what "makes sense", because those aren't always the same thing:

E.g. it arguably "makes sense" for getSettings() and getCapabilities() to have the same number members, and it "makes sense" that inherent and non-inherent properties follow the same rules. But there's little practical utility in it, except maybe listing them in a generic app. 

There's no small irony having to explain the ConstrainablePattern and say this, but it's not clear to me this meets the bar for overriding earlier decisions.

> * Properties that cannot ever be changed, not even theoretically, should not be a capability. One example is displaySurface.

So [deviceId](https://w3c.github.io/mediacapture-main/#dom-mediatrackcapabilities-deviceid) wouldn't be a capability, but [facingMode](https://w3c.github.io/mediacapture-main/#dom-mediatrackcapabilities-facingmode) would, since it says: _"A camera can report multiple facing modes. For example, in a high-end telepresence solution with several cameras facing the user, a camera to the [left](https://w3c.github.io/mediacapture-main/#dom-videofacingmodeenum-left) of the [user](https://w3c.github.io/mediacapture-main/#dom-videofacingmodeenum-user) can report both "left" and "user"."_?

I.e. it can *in theory* be set to [e.g. "user" or "left"](https://w3c.github.io/mediacapture-main/#example-11) (without effect), even though it's an inherent property of the camera.

**Comment by eladalon1983** [comment]
> I.e. it can in theory be set to [e.g. "user" or "left"](https://w3c.github.io/mediacapture-main/#example-11) (without effect), even though it's an inherent property of the camera.

I think it would help to try and see what I meant by "can theoretically be changed." I think reading the rest of the sentence could do the trick here. Here it is: "in a spec-compliant way by calling applyConstraints()."

**Comment by jan-ivar** [comment]
AFAIK the spec says this should work for a hypothetical camera with ["user", "left"] capabilities:
```js
console.log(track.getCapabilities().facingMode); // ["user", "left"]
await track.applyConstraints({facingMode: {exact: "user"}});
console.log(track.getSettings().facingMode); // "user"
await track.applyConstraints({facingMode: {exact: "left"}});
console.log(track.getSettings().facingMode); // "left"
```
Doesn't make a lot of sense, but it means I can't tell what you mean.

**Comment by beaufortfrancois** [comment]
Going back to `displaySurface`, I'm not sure what would be the difference between returning an array of a unique string value and a unique string value. Both can't be changed later with applyConstraints.

```js
// Current situation
console.log(track.getCapabilities().displaySurface); // "monitor", "window", or "browser"
```
```js
// New ?
console.log(track.getCapabilities().displaySurface); // ["monitor"], ["window"], or ["browser"]
```
```js
// This is no-op either way as the displaySurface can't be changed later.
await track.applyConstraints({displaySurface: {exact: "browser"}});
```

In that case, does it make sense to expose the `displaySurface` capability at all? It seems like it goes down to this "make sense" part. I'm not sure either ;)

**Comment by eladalon1983** [comment]
> AFAIK the spec says [...]

As mentioned, I am trying to discuss what the spec **should** say going forward. ("For me, the question is whether the current design makes sense as is, or if it should be amended.")

> Doesn't make a lot of sense

Exactly.

**Comment by beaufortfrancois** [comment]
By the way, I just noticed that `suppressLocalAudioPlayback` and `restrictOwnAudio` were not returned in getCapabilities() while they were in getSettings().

**Comment by jan-ivar** [comment]
> Is it clearer now?

No, you're arguing for changing applyConstraints? Good luck.

**Comment by jan-ivar** [comment]
> Was a conscious decision made by this WG, for inherent properties to be capabilities?

It is deeply ingrained in the [model](https://w3c.github.io/mediacapture-main/#constrainable-interface): _"The core concept is the Capability, which consists of a constrainable property of an object and the set of its possible values, which may be specified either as a range or as an enumeration. For example, a camera might be capable of framerates (a property) between 20 and 50 frames per second (a range) and may be able to be positioned (a property) facing towards the user, away from the user, or to the left or right of the user (an enumerated set). The application can examine a constrainable property's supported Capabilities via the getCapabilities() accessor."_

I don't recall a challenge related to carving out an exception for inherent properties, but there have been many meetings and CfCs since [2013](https://github.com/w3c/mediacapture-main/commit/993a5af6ab0fdc2123339a80922d10782a0dd254) so this is definitely on purpose and decided. I encourage you to do further research.

**Comment by eladalon1983** [comment]
> I don't recall a challenge related to carving out an exception for inherent properties

I don't recall a previous challenge either, so it looks like the information presented in [this comment](https://github.com/w3c/mediacapture-main/issues/915#issue-1435227436) is new, and merits discussion in the WG per its charter.

**Comment by alvestrand** [comment]
It makes no sense to me to have some constraints that don't have capabilities and some constraints that do have it.
That would require programmers (and programs) to read the spec for each individual constraint in order to figure out how to interpret the result of getCapabilities. And I think that's a Bad Idea.

**Comment by eladalon1983** [comment]
Harald, what are programmers expected to do with a capability? The image in [this comment](https://github.com/w3c/mediacapture-main/issues/915#issuecomment-1302634191) shows a credible use case for capabilities, that would benefit of there **not** being a capability for some constraints. What's the inverse use case that shows that matching capabilities to constraints is useful for devs?

**Comment by alvestrand** [comment]
that demo demonstrates the need for having capabilities very well. If some didn't have it, the code would error out on the line that tries to access capabilities, and would have to be extended with an "if (!capabilities)" case. So you've made the point that adding constraints without capabilities would break existing, deployed code.

**Comment by eladalon1983** [comment]
If getCapabiltiies() does not return \"displaySurface\", then the user won't see it as a tweakable control. I don't think that constitutes the demo breaking. I think that's very desirable.
